#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <semaphore.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdarg.h>
#include <unistd.h>
#include <signal.h>
#include <limits.h>
#include <poll.h>
#include <sys/epoll.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <error.h>
#include <errno.h>
#include <sys/ioctl.h>
#include <net/if.h> 
#include <resolv.h>


#ifndef SIRIK_E1AP_TEST_H
#define SIRIK_E1AP_TEST_H

#include "E1AP_18.3.h"
#include "E1AP_18.3_Stack.h"

void __si_e1ap__set_testdata__PrivateIE_ID( SI_E1AP_DT_PrivateIE_ID ** pPrivateIE_ID);
void __si_e1ap__set_testdata__ActivityInformation( SI_E1AP_DT_ActivityInformation ** pActivityInformation);
void __si_e1ap__set_testdata__AlternativeQoSParaSetList( SI_E1AP_DT_AlternativeQoSParaSetList ** pAlternativeQoSParaSetList);
void __si_e1ap__set_testdata__AlternativeQoSParaSetItem( SI_E1AP_DT_AlternativeQoSParaSetItem ** pAlternativeQoSParaSetItem);
void __si_e1ap__set_testdata__BCBearerContextToSetup( SI_E1AP_DT_BCBearerContextToSetup ** pBCBearerContextToSetup);
void __si_e1ap__set_testdata__BCBearerContextNGU_TNLInfoat5GC( SI_E1AP_DT_BCBearerContextNGU_TNLInfoat5GC ** pBCBearerContextNGU_TNLInfoat5GC);
void __si_e1ap__set_testdata__BCMRBSetupConfiguration( SI_E1AP_DT_BCMRBSetupConfiguration ** pBCMRBSetupConfiguration);
void __si_e1ap__set_testdata__BCMRBSetupConfiguration_Item( SI_E1AP_DT_BCMRBSetupConfiguration_Item ** pBCMRBSetupConfiguration_Item);
void __si_e1ap__set_testdata__BCBearerContextToSetupResponse( SI_E1AP_DT_BCBearerContextToSetupResponse ** pBCBearerContextToSetupResponse);
void __si_e1ap__set_testdata__BCBearerContextNGU_TNLInfoatNGRAN( SI_E1AP_DT_BCBearerContextNGU_TNLInfoatNGRAN ** pBCBearerContextNGU_TNLInfoatNGRAN);
void __si_e1ap__set_testdata__BCMRBSetupResponseList( SI_E1AP_DT_BCMRBSetupResponseList ** pBCMRBSetupResponseList);
void __si_e1ap__set_testdata__BCMRBSetupResponseList_Item( SI_E1AP_DT_BCMRBSetupResponseList_Item ** pBCMRBSetupResponseList_Item);
void __si_e1ap__set_testdata__BCBearerContextF1U_TNLInfoatCU( SI_E1AP_DT_BCBearerContextF1U_TNLInfoatCU ** pBCBearerContextF1U_TNLInfoatCU);
void __si_e1ap__set_testdata__BCMRBFailedList( SI_E1AP_DT_BCMRBFailedList ** pBCMRBFailedList);
void __si_e1ap__set_testdata__BCMRBFailedList_Item( SI_E1AP_DT_BCMRBFailedList_Item ** pBCMRBFailedList_Item);
void __si_e1ap__set_testdata__BCBearerContextToModify( SI_E1AP_DT_BCBearerContextToModify ** pBCBearerContextToModify);
void __si_e1ap__set_testdata__BCBearerContextNGU_TNLInfoatNGRAN_Request( SI_E1AP_DT_BCBearerContextNGU_TNLInfoatNGRAN_Request ** pBCBearerContextNGU_TNLInfoatNGRAN_Request);
void __si_e1ap__set_testdata__BCMRBModifyConfiguration( SI_E1AP_DT_BCMRBModifyConfiguration ** pBCMRBModifyConfiguration);
void __si_e1ap__set_testdata__BCMRBModifyConfiguration_Item( SI_E1AP_DT_BCMRBModifyConfiguration_Item ** pBCMRBModifyConfiguration_Item);
void __si_e1ap__set_testdata__BCBearerContextF1U_TNLInfoatDU( SI_E1AP_DT_BCBearerContextF1U_TNLInfoatDU ** pBCBearerContextF1U_TNLInfoatDU);
void __si_e1ap__set_testdata__BCMRBRemoveConfiguration( SI_E1AP_DT_BCMRBRemoveConfiguration ** pBCMRBRemoveConfiguration);
void __si_e1ap__set_testdata__BCBearerContextToModifyResponse( SI_E1AP_DT_BCBearerContextToModifyResponse ** pBCBearerContextToModifyResponse);
void __si_e1ap__set_testdata__BCMRBSetupModifyResponseList( SI_E1AP_DT_BCMRBSetupModifyResponseList ** pBCMRBSetupModifyResponseList);
void __si_e1ap__set_testdata__BCMRBSetupModifyResponseList_Item( SI_E1AP_DT_BCMRBSetupModifyResponseList_Item ** pBCMRBSetupModifyResponseList_Item);
void __si_e1ap__set_testdata__BCBearerContextToModifyRequired( SI_E1AP_DT_BCBearerContextToModifyRequired ** pBCBearerContextToModifyRequired);
void __si_e1ap__set_testdata__BCBearerContextToModifyConfirm( SI_E1AP_DT_BCBearerContextToModifyConfirm ** pBCBearerContextToModifyConfirm);
void __si_e1ap__set_testdata__Cause( SI_E1AP_DT_Cause ** pCause);
void __si_e1ap__set_testdata__Cell_Group_Information( SI_E1AP_DT_Cell_Group_Information ** pCell_Group_Information);
void __si_e1ap__set_testdata__Cell_Group_Information_Item( SI_E1AP_DT_Cell_Group_Information_Item ** pCell_Group_Information_Item);
void __si_e1ap__set_testdata__CP_TNL_Information( SI_E1AP_DT_CP_TNL_Information ** pCP_TNL_Information);
void __si_e1ap__set_testdata__CriticalityDiagnostics( SI_E1AP_DT_CriticalityDiagnostics ** pCriticalityDiagnostics);
void __si_e1ap__set_testdata__DAPSRequestInfo( SI_E1AP_DT_DAPSRequestInfo ** pDAPSRequestInfo);
void __si_e1ap__set_testdata__Data_Forwarding_Information_Request( SI_E1AP_DT_Data_Forwarding_Information_Request ** pData_Forwarding_Information_Request);
void __si_e1ap__set_testdata__Data_Forwarding_Information( SI_E1AP_DT_Data_Forwarding_Information ** pData_Forwarding_Information);
void __si_e1ap__set_testdata__DataForwardingtoE_UTRANInformationList( SI_E1AP_DT_DataForwardingtoE_UTRANInformationList ** pDataForwardingtoE_UTRANInformationList);
void __si_e1ap__set_testdata__DataForwardingtoE_UTRANInformationListItem( SI_E1AP_DT_DataForwardingtoE_UTRANInformationListItem ** pDataForwardingtoE_UTRANInformationListItem);
void __si_e1ap__set_testdata__DataUsageperPDUSessionReport_pDU_session_Timed_Report_List( SI_E1AP_DT_DataUsageperPDUSessionReport_pDU_session_Timed_Report_List ** pDataUsageperPDUSessionReport_pDU_session_Timed_Report_List);
void __si_e1ap__set_testdata__Data_Usage_per_PDU_Session_Report( SI_E1AP_DT_Data_Usage_per_PDU_Session_Report ** pData_Usage_per_PDU_Session_Report);
void __si_e1ap__set_testdata__Data_Usage_per_QoS_Flow_List( SI_E1AP_DT_Data_Usage_per_QoS_Flow_List ** pData_Usage_per_QoS_Flow_List);
void __si_e1ap__set_testdata__DataUsageperQoSFlowItem_qoS_Flow_Timed_Report_List( SI_E1AP_DT_DataUsageperQoSFlowItem_qoS_Flow_Timed_Report_List ** pDataUsageperQoSFlowItem_qoS_Flow_Timed_Report_List);
void __si_e1ap__set_testdata__Data_Usage_per_QoS_Flow_Item( SI_E1AP_DT_Data_Usage_per_QoS_Flow_Item ** pData_Usage_per_QoS_Flow_Item);
void __si_e1ap__set_testdata__Data_Usage_Report_List( SI_E1AP_DT_Data_Usage_Report_List ** pData_Usage_Report_List);
void __si_e1ap__set_testdata__Data_Usage_Report_Item( SI_E1AP_DT_Data_Usage_Report_Item ** pData_Usage_Report_Item);
void __si_e1ap__set_testdata__DLDiscarding( SI_E1AP_DT_DLDiscarding ** pDLDiscarding);
void __si_e1ap__set_testdata__DLUPTNLAddressToUpdateItem( SI_E1AP_DT_DLUPTNLAddressToUpdateItem ** pDLUPTNLAddressToUpdateItem);
void __si_e1ap__set_testdata__DRB_Activity_List( SI_E1AP_DT_DRB_Activity_List ** pDRB_Activity_List);
void __si_e1ap__set_testdata__DRB_Activity_Item( SI_E1AP_DT_DRB_Activity_Item ** pDRB_Activity_Item);
void __si_e1ap__set_testdata__DRB_Confirm_Modified_List_EUTRAN( SI_E1AP_DT_DRB_Confirm_Modified_List_EUTRAN ** pDRB_Confirm_Modified_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Confirm_Modified_Item_EUTRAN( SI_E1AP_DT_DRB_Confirm_Modified_Item_EUTRAN ** pDRB_Confirm_Modified_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Confirm_Modified_List_NG_RAN( SI_E1AP_DT_DRB_Confirm_Modified_List_NG_RAN ** pDRB_Confirm_Modified_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Confirm_Modified_Item_NG_RAN( SI_E1AP_DT_DRB_Confirm_Modified_Item_NG_RAN ** pDRB_Confirm_Modified_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Failed_List_EUTRAN( SI_E1AP_DT_DRB_Failed_List_EUTRAN ** pDRB_Failed_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Failed_Item_EUTRAN( SI_E1AP_DT_DRB_Failed_Item_EUTRAN ** pDRB_Failed_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Failed_Mod_List_EUTRAN( SI_E1AP_DT_DRB_Failed_Mod_List_EUTRAN ** pDRB_Failed_Mod_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Failed_Mod_Item_EUTRAN( SI_E1AP_DT_DRB_Failed_Mod_Item_EUTRAN ** pDRB_Failed_Mod_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Failed_List_NG_RAN( SI_E1AP_DT_DRB_Failed_List_NG_RAN ** pDRB_Failed_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Failed_Item_NG_RAN( SI_E1AP_DT_DRB_Failed_Item_NG_RAN ** pDRB_Failed_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Failed_Mod_List_NG_RAN( SI_E1AP_DT_DRB_Failed_Mod_List_NG_RAN ** pDRB_Failed_Mod_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Failed_Mod_Item_NG_RAN( SI_E1AP_DT_DRB_Failed_Mod_Item_NG_RAN ** pDRB_Failed_Mod_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Failed_To_Modify_List_EUTRAN( SI_E1AP_DT_DRB_Failed_To_Modify_List_EUTRAN ** pDRB_Failed_To_Modify_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Failed_To_Modify_Item_EUTRAN( SI_E1AP_DT_DRB_Failed_To_Modify_Item_EUTRAN ** pDRB_Failed_To_Modify_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Failed_To_Modify_List_NG_RAN( SI_E1AP_DT_DRB_Failed_To_Modify_List_NG_RAN ** pDRB_Failed_To_Modify_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Failed_To_Modify_Item_NG_RAN( SI_E1AP_DT_DRB_Failed_To_Modify_Item_NG_RAN ** pDRB_Failed_To_Modify_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Measurement_Results_Information_List( SI_E1AP_DT_DRB_Measurement_Results_Information_List ** pDRB_Measurement_Results_Information_List);
void __si_e1ap__set_testdata__DRB_Measurement_Results_Information_Item( SI_E1AP_DT_DRB_Measurement_Results_Information_Item ** pDRB_Measurement_Results_Information_Item);
void __si_e1ap__set_testdata__DRB_Modified_List_EUTRAN( SI_E1AP_DT_DRB_Modified_List_EUTRAN ** pDRB_Modified_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Modified_Item_EUTRAN( SI_E1AP_DT_DRB_Modified_Item_EUTRAN ** pDRB_Modified_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Modified_List_NG_RAN( SI_E1AP_DT_DRB_Modified_List_NG_RAN ** pDRB_Modified_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Modified_Item_NG_RAN( SI_E1AP_DT_DRB_Modified_Item_NG_RAN ** pDRB_Modified_Item_NG_RAN);
void __si_e1ap__set_testdata__DRBRemovedItem_qoS_Flow_Removed_List( SI_E1AP_DT_DRBRemovedItem_qoS_Flow_Removed_List ** pDRBRemovedItem_qoS_Flow_Removed_List);
void __si_e1ap__set_testdata__DRB_Removed_Item( SI_E1AP_DT_DRB_Removed_Item ** pDRB_Removed_Item);
void __si_e1ap__set_testdata__DRB_Required_To_Modify_List_EUTRAN( SI_E1AP_DT_DRB_Required_To_Modify_List_EUTRAN ** pDRB_Required_To_Modify_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Required_To_Modify_Item_EUTRAN( SI_E1AP_DT_DRB_Required_To_Modify_Item_EUTRAN ** pDRB_Required_To_Modify_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Required_To_Modify_List_NG_RAN( SI_E1AP_DT_DRB_Required_To_Modify_List_NG_RAN ** pDRB_Required_To_Modify_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Required_To_Modify_Item_NG_RAN( SI_E1AP_DT_DRB_Required_To_Modify_Item_NG_RAN ** pDRB_Required_To_Modify_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Setup_List_EUTRAN( SI_E1AP_DT_DRB_Setup_List_EUTRAN ** pDRB_Setup_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Setup_Item_EUTRAN( SI_E1AP_DT_DRB_Setup_Item_EUTRAN ** pDRB_Setup_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Setup_Mod_List_EUTRAN( SI_E1AP_DT_DRB_Setup_Mod_List_EUTRAN ** pDRB_Setup_Mod_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Setup_Mod_Item_EUTRAN( SI_E1AP_DT_DRB_Setup_Mod_Item_EUTRAN ** pDRB_Setup_Mod_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Setup_List_NG_RAN( SI_E1AP_DT_DRB_Setup_List_NG_RAN ** pDRB_Setup_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Setup_Item_NG_RAN( SI_E1AP_DT_DRB_Setup_Item_NG_RAN ** pDRB_Setup_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Setup_Mod_List_NG_RAN( SI_E1AP_DT_DRB_Setup_Mod_List_NG_RAN ** pDRB_Setup_Mod_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Setup_Mod_Item_NG_RAN( SI_E1AP_DT_DRB_Setup_Mod_Item_NG_RAN ** pDRB_Setup_Mod_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Status_Item( SI_E1AP_DT_DRB_Status_Item ** pDRB_Status_Item);
void __si_e1ap__set_testdata__DRBs_Subject_To_Counter_Check_List_EUTRAN( SI_E1AP_DT_DRBs_Subject_To_Counter_Check_List_EUTRAN ** pDRBs_Subject_To_Counter_Check_List_EUTRAN);
void __si_e1ap__set_testdata__DRBs_Subject_To_Counter_Check_Item_EUTRAN( SI_E1AP_DT_DRBs_Subject_To_Counter_Check_Item_EUTRAN ** pDRBs_Subject_To_Counter_Check_Item_EUTRAN);
void __si_e1ap__set_testdata__DRBs_Subject_To_Counter_Check_List_NG_RAN( SI_E1AP_DT_DRBs_Subject_To_Counter_Check_List_NG_RAN ** pDRBs_Subject_To_Counter_Check_List_NG_RAN);
void __si_e1ap__set_testdata__DRBs_Subject_To_Counter_Check_Item_NG_RAN( SI_E1AP_DT_DRBs_Subject_To_Counter_Check_Item_NG_RAN ** pDRBs_Subject_To_Counter_Check_Item_NG_RAN);
void __si_e1ap__set_testdata__DRBs_Subject_To_Early_Forwarding_List( SI_E1AP_DT_DRBs_Subject_To_Early_Forwarding_List ** pDRBs_Subject_To_Early_Forwarding_List);
void __si_e1ap__set_testdata__DRBs_Subject_To_Early_Forwarding_Item( SI_E1AP_DT_DRBs_Subject_To_Early_Forwarding_Item ** pDRBs_Subject_To_Early_Forwarding_Item);
void __si_e1ap__set_testdata__DRB_To_Modify_List_EUTRAN( SI_E1AP_DT_DRB_To_Modify_List_EUTRAN ** pDRB_To_Modify_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_To_Modify_Item_EUTRAN( SI_E1AP_DT_DRB_To_Modify_Item_EUTRAN ** pDRB_To_Modify_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_To_Modify_List_NG_RAN( SI_E1AP_DT_DRB_To_Modify_List_NG_RAN ** pDRB_To_Modify_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_To_Modify_Item_NG_RAN( SI_E1AP_DT_DRB_To_Modify_Item_NG_RAN ** pDRB_To_Modify_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_To_Remove_List_EUTRAN( SI_E1AP_DT_DRB_To_Remove_List_EUTRAN ** pDRB_To_Remove_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_To_Remove_Item_EUTRAN( SI_E1AP_DT_DRB_To_Remove_Item_EUTRAN ** pDRB_To_Remove_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_Required_To_Remove_List_EUTRAN( SI_E1AP_DT_DRB_Required_To_Remove_List_EUTRAN ** pDRB_Required_To_Remove_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_Required_To_Remove_Item_EUTRAN( SI_E1AP_DT_DRB_Required_To_Remove_Item_EUTRAN ** pDRB_Required_To_Remove_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_To_Remove_List_NG_RAN( SI_E1AP_DT_DRB_To_Remove_List_NG_RAN ** pDRB_To_Remove_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_To_Remove_Item_NG_RAN( SI_E1AP_DT_DRB_To_Remove_Item_NG_RAN ** pDRB_To_Remove_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Required_To_Remove_List_NG_RAN( SI_E1AP_DT_DRB_Required_To_Remove_List_NG_RAN ** pDRB_Required_To_Remove_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_Required_To_Remove_Item_NG_RAN( SI_E1AP_DT_DRB_Required_To_Remove_Item_NG_RAN ** pDRB_Required_To_Remove_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_To_Setup_List_EUTRAN( SI_E1AP_DT_DRB_To_Setup_List_EUTRAN ** pDRB_To_Setup_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_To_Setup_Item_EUTRAN( SI_E1AP_DT_DRB_To_Setup_Item_EUTRAN ** pDRB_To_Setup_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_To_Setup_Mod_List_EUTRAN( SI_E1AP_DT_DRB_To_Setup_Mod_List_EUTRAN ** pDRB_To_Setup_Mod_List_EUTRAN);
void __si_e1ap__set_testdata__DRB_To_Setup_Mod_Item_EUTRAN( SI_E1AP_DT_DRB_To_Setup_Mod_Item_EUTRAN ** pDRB_To_Setup_Mod_Item_EUTRAN);
void __si_e1ap__set_testdata__DRB_To_Setup_List_NG_RAN( SI_E1AP_DT_DRB_To_Setup_List_NG_RAN ** pDRB_To_Setup_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_To_Setup_Item_NG_RAN( SI_E1AP_DT_DRB_To_Setup_Item_NG_RAN ** pDRB_To_Setup_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_To_Setup_Mod_List_NG_RAN( SI_E1AP_DT_DRB_To_Setup_Mod_List_NG_RAN ** pDRB_To_Setup_Mod_List_NG_RAN);
void __si_e1ap__set_testdata__DRB_To_Setup_Mod_Item_NG_RAN( SI_E1AP_DT_DRB_To_Setup_Mod_Item_NG_RAN ** pDRB_To_Setup_Mod_Item_NG_RAN);
void __si_e1ap__set_testdata__DRB_Usage_Report_List( SI_E1AP_DT_DRB_Usage_Report_List ** pDRB_Usage_Report_List);
void __si_e1ap__set_testdata__DRB_Usage_Report_Item( SI_E1AP_DT_DRB_Usage_Report_Item ** pDRB_Usage_Report_Item);
void __si_e1ap__set_testdata__Dynamic5QIDescriptor( SI_E1AP_DT_Dynamic5QIDescriptor ** pDynamic5QIDescriptor);
void __si_e1ap__set_testdata__EarlyForwardingCOUNTInfo( SI_E1AP_DT_EarlyForwardingCOUNTInfo ** pEarlyForwardingCOUNTInfo);
void __si_e1ap__set_testdata__ECNMarkingorCongestionInformationReportingRequest( SI_E1AP_DT_ECNMarkingorCongestionInformationReportingRequest ** pECNMarkingorCongestionInformationReportingRequest);
void __si_e1ap__set_testdata__EHC_Common_Parameters( SI_E1AP_DT_EHC_Common_Parameters ** pEHC_Common_Parameters);
void __si_e1ap__set_testdata__EHC_Downlink_Parameters( SI_E1AP_DT_EHC_Downlink_Parameters ** pEHC_Downlink_Parameters);
void __si_e1ap__set_testdata__EHC_Uplink_Parameters( SI_E1AP_DT_EHC_Uplink_Parameters ** pEHC_Uplink_Parameters);
void __si_e1ap__set_testdata__EHC_Parameters( SI_E1AP_DT_EHC_Parameters ** pEHC_Parameters);
void __si_e1ap__set_testdata__Endpoint_IP_address_and_port( SI_E1AP_DT_Endpoint_IP_address_and_port ** pEndpoint_IP_address_and_port);
void __si_e1ap__set_testdata__EUTRANAllocationAndRetentionPriority( SI_E1AP_DT_EUTRANAllocationAndRetentionPriority ** pEUTRANAllocationAndRetentionPriority);
void __si_e1ap__set_testdata__ECGI( SI_E1AP_DT_ECGI ** pECGI);
void __si_e1ap__set_testdata__ECGI_Support_List( SI_E1AP_DT_ECGI_Support_List ** pECGI_Support_List);
void __si_e1ap__set_testdata__ECGI_Support_Item( SI_E1AP_DT_ECGI_Support_Item ** pECGI_Support_Item);
void __si_e1ap__set_testdata__EUTRAN_QoS_Support_List( SI_E1AP_DT_EUTRAN_QoS_Support_List ** pEUTRAN_QoS_Support_List);
void __si_e1ap__set_testdata__EUTRAN_QoS_Support_Item( SI_E1AP_DT_EUTRAN_QoS_Support_Item ** pEUTRAN_QoS_Support_Item);
void __si_e1ap__set_testdata__EUTRAN_QoS( SI_E1AP_DT_EUTRAN_QoS ** pEUTRAN_QoS);
void __si_e1ap__set_testdata__ExtendedSliceSupportList( SI_E1AP_DT_ExtendedSliceSupportList ** pExtendedSliceSupportList);
void __si_e1ap__set_testdata__FirstDLCount( SI_E1AP_DT_FirstDLCount ** pFirstDLCount);
void __si_e1ap__set_testdata__F1U_TNL_InfoAdded_List( SI_E1AP_DT_F1U_TNL_InfoAdded_List ** pF1U_TNL_InfoAdded_List);
void __si_e1ap__set_testdata__F1U_TNL_InfoAdded_Item( SI_E1AP_DT_F1U_TNL_InfoAdded_Item ** pF1U_TNL_InfoAdded_Item);
void __si_e1ap__set_testdata__F1U_TNL_InfoToAdd_List( SI_E1AP_DT_F1U_TNL_InfoToAdd_List ** pF1U_TNL_InfoToAdd_List);
void __si_e1ap__set_testdata__F1U_TNL_InfoToAdd_Item( SI_E1AP_DT_F1U_TNL_InfoToAdd_Item ** pF1U_TNL_InfoToAdd_Item);
void __si_e1ap__set_testdata__F1U_TNL_InfoAddedOrModified_List( SI_E1AP_DT_F1U_TNL_InfoAddedOrModified_List ** pF1U_TNL_InfoAddedOrModified_List);
void __si_e1ap__set_testdata__F1U_TNL_InfoAddedOrModified_Item( SI_E1AP_DT_F1U_TNL_InfoAddedOrModified_Item ** pF1U_TNL_InfoAddedOrModified_Item);
void __si_e1ap__set_testdata__F1U_TNL_InfoToAddOrModify_List( SI_E1AP_DT_F1U_TNL_InfoToAddOrModify_List ** pF1U_TNL_InfoToAddOrModify_List);
void __si_e1ap__set_testdata__F1U_TNL_InfoToAddOrModify_Item( SI_E1AP_DT_F1U_TNL_InfoToAddOrModify_Item ** pF1U_TNL_InfoToAddOrModify_Item);
void __si_e1ap__set_testdata__F1U_TNL_InfoToRelease_List( SI_E1AP_DT_F1U_TNL_InfoToRelease_List ** pF1U_TNL_InfoToRelease_List);
void __si_e1ap__set_testdata__F1U_TNL_InfoToRelease_Item( SI_E1AP_DT_F1U_TNL_InfoToRelease_Item ** pF1U_TNL_InfoToRelease_Item);
void __si_e1ap__set_testdata__GlobalMBSSessionID( SI_E1AP_DT_GlobalMBSSessionID ** pGlobalMBSSessionID);
void __si_e1ap__set_testdata__Extended_GNB_CU_CP_Name( SI_E1AP_DT_Extended_GNB_CU_CP_Name ** pExtended_GNB_CU_CP_Name);
void __si_e1ap__set_testdata__GNB_CU_UP_CellGroupRelatedConfiguration( SI_E1AP_DT_GNB_CU_UP_CellGroupRelatedConfiguration ** pGNB_CU_UP_CellGroupRelatedConfiguration);
void __si_e1ap__set_testdata__GNB_CU_UP_CellGroupRelatedConfiguration_Item( SI_E1AP_DT_GNB_CU_UP_CellGroupRelatedConfiguration_Item ** pGNB_CU_UP_CellGroupRelatedConfiguration_Item);
void __si_e1ap__set_testdata__GNB_CU_UP_MBS_Support_Info( SI_E1AP_DT_GNB_CU_UP_MBS_Support_Info ** pGNB_CU_UP_MBS_Support_Info);
void __si_e1ap__set_testdata__Extended_GNB_CU_UP_Name( SI_E1AP_DT_Extended_GNB_CU_UP_Name ** pExtended_GNB_CU_UP_Name);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_Setup_Item( SI_E1AP_DT_GNB_CU_CP_TNLA_Setup_Item ** pGNB_CU_CP_TNLA_Setup_Item);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_Failed_To_Setup_Item( SI_E1AP_DT_GNB_CU_CP_TNLA_Failed_To_Setup_Item ** pGNB_CU_CP_TNLA_Failed_To_Setup_Item);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_To_Add_Item( SI_E1AP_DT_GNB_CU_CP_TNLA_To_Add_Item ** pGNB_CU_CP_TNLA_To_Add_Item);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_To_Remove_Item( SI_E1AP_DT_GNB_CU_CP_TNLA_To_Remove_Item ** pGNB_CU_CP_TNLA_To_Remove_Item);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_To_Update_Item( SI_E1AP_DT_GNB_CU_CP_TNLA_To_Update_Item ** pGNB_CU_CP_TNLA_To_Update_Item);
void __si_e1ap__set_testdata__GNB_CU_UP_TNLA_To_Remove_Item( SI_E1AP_DT_GNB_CU_UP_TNLA_To_Remove_Item ** pGNB_CU_UP_TNLA_To_Remove_Item);
void __si_e1ap__set_testdata__GBR_QosInformation( SI_E1AP_DT_GBR_QosInformation ** pGBR_QosInformation);
void __si_e1ap__set_testdata__GBR_QoSFlowInformation( SI_E1AP_DT_GBR_QoSFlowInformation ** pGBR_QoSFlowInformation);
void __si_e1ap__set_testdata__GTPTLAs( SI_E1AP_DT_GTPTLAs ** pGTPTLAs);
void __si_e1ap__set_testdata__GTPTLA_Item( SI_E1AP_DT_GTPTLA_Item ** pGTPTLA_Item);
void __si_e1ap__set_testdata__GTPTunnel( SI_E1AP_DT_GTPTunnel ** pGTPTunnel);
void __si_e1ap__set_testdata__HW_CapacityIndicator( SI_E1AP_DT_HW_CapacityIndicator ** pHW_CapacityIndicator);
void __si_e1ap__set_testdata__ImmediateMDT( SI_E1AP_DT_ImmediateMDT ** pImmediateMDT);
void __si_e1ap__set_testdata__IAB_Donor_CU_UPPSKInfo_Item( SI_E1AP_DT_IAB_Donor_CU_UPPSKInfo_Item ** pIAB_Donor_CU_UPPSKInfo_Item);
void __si_e1ap__set_testdata__LocationDependentMBSNGUInformationAt5GC( SI_E1AP_DT_LocationDependentMBSNGUInformationAt5GC ** pLocationDependentMBSNGUInformationAt5GC);
void __si_e1ap__set_testdata__LocationDependentMBSNGUInformationAt5GC_Item( SI_E1AP_DT_LocationDependentMBSNGUInformationAt5GC_Item ** pLocationDependentMBSNGUInformationAt5GC_Item);
void __si_e1ap__set_testdata__LocationDependentMBSF1UInformationAtCU( SI_E1AP_DT_LocationDependentMBSF1UInformationAtCU ** pLocationDependentMBSF1UInformationAtCU);
void __si_e1ap__set_testdata__LocationDependentMBSF1UInformationAtCU_Item( SI_E1AP_DT_LocationDependentMBSF1UInformationAtCU_Item ** pLocationDependentMBSF1UInformationAtCU_Item);
void __si_e1ap__set_testdata__LocationDependentMBSF1UInformationAtDU( SI_E1AP_DT_LocationDependentMBSF1UInformationAtDU ** pLocationDependentMBSF1UInformationAtDU);
void __si_e1ap__set_testdata__LocationDependentMBSF1UInformationAtDU_Item( SI_E1AP_DT_LocationDependentMBSF1UInformationAtDU_Item ** pLocationDependentMBSF1UInformationAtDU_Item);
void __si_e1ap__set_testdata__LocationDependentMBSNGUInformationAtNGRAN( SI_E1AP_DT_LocationDependentMBSNGUInformationAtNGRAN ** pLocationDependentMBSNGUInformationAtNGRAN);
void __si_e1ap__set_testdata__LocationDependentMBSNGUInformationAtNGRAN_Item( SI_E1AP_DT_LocationDependentMBSNGUInformationAtNGRAN_Item ** pLocationDependentMBSNGUInformationAtNGRAN_Item);
void __si_e1ap__set_testdata__MaximumIPdatarate( SI_E1AP_DT_MaximumIPdatarate ** pMaximumIPdatarate);
void __si_e1ap__set_testdata__MBSF1UInformationAtCU( SI_E1AP_DT_MBSF1UInformationAtCU ** pMBSF1UInformationAtCU);
void __si_e1ap__set_testdata__MBSF1UInformationAtDU( SI_E1AP_DT_MBSF1UInformationAtDU ** pMBSF1UInformationAtDU);
void __si_e1ap__set_testdata__MBSNGUInformationAt5GC( SI_E1AP_DT_MBSNGUInformationAt5GC ** pMBSNGUInformationAt5GC);
void __si_e1ap__set_testdata__MBSNGUInformationAt5GC_Multicast( SI_E1AP_DT_MBSNGUInformationAt5GC_Multicast ** pMBSNGUInformationAt5GC_Multicast);
void __si_e1ap__set_testdata__MBSNGUInformationAtNGRAN( SI_E1AP_DT_MBSNGUInformationAtNGRAN ** pMBSNGUInformationAtNGRAN);
void __si_e1ap__set_testdata__MBSNGUInformationAtNGRAN_Request_List( SI_E1AP_DT_MBSNGUInformationAtNGRAN_Request_List ** pMBSNGUInformationAtNGRAN_Request_List);
void __si_e1ap__set_testdata__MBSNGUInformationAtNGRAN_Request_Item( SI_E1AP_DT_MBSNGUInformationAtNGRAN_Request_Item ** pMBSNGUInformationAtNGRAN_Request_Item);
void __si_e1ap__set_testdata__MBSSessionAssociatedInfoNonSupportToSupport( SI_E1AP_DT_MBSSessionAssociatedInfoNonSupportToSupport ** pMBSSessionAssociatedInfoNonSupportToSupport);
void __si_e1ap__set_testdata__MBSSessionAssociatedInformation( SI_E1AP_DT_MBSSessionAssociatedInformation ** pMBSSessionAssociatedInformation);
void __si_e1ap__set_testdata__MBSSessionAssociatedInformationList( SI_E1AP_DT_MBSSessionAssociatedInformationList ** pMBSSessionAssociatedInformationList);
void __si_e1ap__set_testdata__MBSSessionAssociatedInformation_Item( SI_E1AP_DT_MBSSessionAssociatedInformation_Item ** pMBSSessionAssociatedInformation_Item);
void __si_e1ap__set_testdata__MBS_Support_Info_ToAdd_List( SI_E1AP_DT_MBS_Support_Info_ToAdd_List ** pMBS_Support_Info_ToAdd_List);
void __si_e1ap__set_testdata__MBS_Support_Info_ToAdd_Item( SI_E1AP_DT_MBS_Support_Info_ToAdd_Item ** pMBS_Support_Info_ToAdd_Item);
void __si_e1ap__set_testdata__MBS_Support_Info_ToRemove_List( SI_E1AP_DT_MBS_Support_Info_ToRemove_List ** pMBS_Support_Info_ToRemove_List);
void __si_e1ap__set_testdata__MBSSessionResourceNotification( SI_E1AP_DT_MBSSessionResourceNotification ** pMBSSessionResourceNotification);
void __si_e1ap__set_testdata__MBS_DL_Data_Arrival( SI_E1AP_DT_MBS_DL_Data_Arrival ** pMBS_DL_Data_Arrival);
void __si_e1ap__set_testdata__MCBearerContext_Inactivity( SI_E1AP_DT_MCBearerContext_Inactivity ** pMCBearerContext_Inactivity);
void __si_e1ap__set_testdata__MBS_Support_Info_ToRemove_Item( SI_E1AP_DT_MBS_Support_Info_ToRemove_Item ** pMBS_Support_Info_ToRemove_Item);
void __si_e1ap__set_testdata__MCBearerContextToSetup( SI_E1AP_DT_MCBearerContextToSetup ** pMCBearerContextToSetup);
void __si_e1ap__set_testdata__MCMRBSetupConfiguration( SI_E1AP_DT_MCMRBSetupConfiguration ** pMCMRBSetupConfiguration);
void __si_e1ap__set_testdata__MCMRBSetupConfiguration_Item( SI_E1AP_DT_MCMRBSetupConfiguration_Item ** pMCMRBSetupConfiguration_Item);
void __si_e1ap__set_testdata__MCBearerContextToSetupResponse( SI_E1AP_DT_MCBearerContextToSetupResponse ** pMCBearerContextToSetupResponse);
void __si_e1ap__set_testdata__MCBearerContextNGU_TNLInfoatNGRAN( SI_E1AP_DT_MCBearerContextNGU_TNLInfoatNGRAN ** pMCBearerContextNGU_TNLInfoatNGRAN);
void __si_e1ap__set_testdata__MCMRBSetupResponseList( SI_E1AP_DT_MCMRBSetupResponseList ** pMCMRBSetupResponseList);
void __si_e1ap__set_testdata__MCMRBSetupResponseList_Item( SI_E1AP_DT_MCMRBSetupResponseList_Item ** pMCMRBSetupResponseList_Item);
void __si_e1ap__set_testdata__MCMRBFailedList( SI_E1AP_DT_MCMRBFailedList ** pMCMRBFailedList);
void __si_e1ap__set_testdata__MCMRBFailedList_Item( SI_E1AP_DT_MCMRBFailedList_Item ** pMCMRBFailedList_Item);
void __si_e1ap__set_testdata__MCBearerContextToModify( SI_E1AP_DT_MCBearerContextToModify ** pMCBearerContextToModify);
void __si_e1ap__set_testdata__MCBearerContextNGUTNLInfoat5GC( SI_E1AP_DT_MCBearerContextNGUTNLInfoat5GC ** pMCBearerContextNGUTNLInfoat5GC);
void __si_e1ap__set_testdata__MCBearerContextNGUTnlInfoatNGRANRequest( SI_E1AP_DT_MCBearerContextNGUTnlInfoatNGRANRequest ** pMCBearerContextNGUTnlInfoatNGRANRequest);
void __si_e1ap__set_testdata__MCMRBSetupModifyConfiguration( SI_E1AP_DT_MCMRBSetupModifyConfiguration ** pMCMRBSetupModifyConfiguration);
void __si_e1ap__set_testdata__MCMRBSetupModifyConfiguration_Item( SI_E1AP_DT_MCMRBSetupModifyConfiguration_Item ** pMCMRBSetupModifyConfiguration_Item);
void __si_e1ap__set_testdata__MCBearerContextF1UTNLInfoatDU( SI_E1AP_DT_MCBearerContextF1UTNLInfoatDU ** pMCBearerContextF1UTNLInfoatDU);
void __si_e1ap__set_testdata__MBSMulticastF1UContextDescriptor( SI_E1AP_DT_MBSMulticastF1UContextDescriptor ** pMBSMulticastF1UContextDescriptor);
void __si_e1ap__set_testdata__MCMRBRemoveConfiguration( SI_E1AP_DT_MCMRBRemoveConfiguration ** pMCMRBRemoveConfiguration);
void __si_e1ap__set_testdata__MCBearerContextToModifyResponse( SI_E1AP_DT_MCBearerContextToModifyResponse ** pMCBearerContextToModifyResponse);
void __si_e1ap__set_testdata__MCBearerContextNGU_TNLInfoatNGRANModifyResponse( SI_E1AP_DT_MCBearerContextNGU_TNLInfoatNGRANModifyResponse ** pMCBearerContextNGU_TNLInfoatNGRANModifyResponse);
void __si_e1ap__set_testdata__MCMRBSetupModifyResponseList( SI_E1AP_DT_MCMRBSetupModifyResponseList ** pMCMRBSetupModifyResponseList);
void __si_e1ap__set_testdata__MCMRBSetupModifyResponseList_Item( SI_E1AP_DT_MCMRBSetupModifyResponseList_Item ** pMCMRBSetupModifyResponseList_Item);
void __si_e1ap__set_testdata__MCBearerContextToModifyRequired( SI_E1AP_DT_MCBearerContextToModifyRequired ** pMCBearerContextToModifyRequired);
void __si_e1ap__set_testdata__MCMRBModifyRequiredConfiguration( SI_E1AP_DT_MCMRBModifyRequiredConfiguration ** pMCMRBModifyRequiredConfiguration);
void __si_e1ap__set_testdata__MCMRBModifyRequiredConfiguration_Item( SI_E1AP_DT_MCMRBModifyRequiredConfiguration_Item ** pMCMRBModifyRequiredConfiguration_Item);
void __si_e1ap__set_testdata__MCBearerContextToModifyConfirm( SI_E1AP_DT_MCBearerContextToModifyConfirm ** pMCBearerContextToModifyConfirm);
void __si_e1ap__set_testdata__MCMRBModifyConfirmList( SI_E1AP_DT_MCMRBModifyConfirmList ** pMCMRBModifyConfirmList);
void __si_e1ap__set_testdata__MCMRBModifyConfirmList_Item( SI_E1AP_DT_MCMRBModifyConfirmList_Item ** pMCMRBModifyConfirmList_Item);
void __si_e1ap__set_testdata__MCForwardingResourceRequest( SI_E1AP_DT_MCForwardingResourceRequest ** pMCForwardingResourceRequest);
void __si_e1ap__set_testdata__MRBForwardingResourceRequestList( SI_E1AP_DT_MRBForwardingResourceRequestList ** pMRBForwardingResourceRequestList);
void __si_e1ap__set_testdata__MRBForwardingResourceRequest_Item( SI_E1AP_DT_MRBForwardingResourceRequest_Item ** pMRBForwardingResourceRequest_Item);
void __si_e1ap__set_testdata__MCForwardingResourceIndication( SI_E1AP_DT_MCForwardingResourceIndication ** pMCForwardingResourceIndication);
void __si_e1ap__set_testdata__MRBForwardingResourceIndicationList( SI_E1AP_DT_MRBForwardingResourceIndicationList ** pMRBForwardingResourceIndicationList);
void __si_e1ap__set_testdata__MRBForwardingResourceIndication_Item( SI_E1AP_DT_MRBForwardingResourceIndication_Item ** pMRBForwardingResourceIndication_Item);
void __si_e1ap__set_testdata__MCForwardingResourceResponse( SI_E1AP_DT_MCForwardingResourceResponse ** pMCForwardingResourceResponse);
void __si_e1ap__set_testdata__MRBForwardingResourceResponseList( SI_E1AP_DT_MRBForwardingResourceResponseList ** pMRBForwardingResourceResponseList);
void __si_e1ap__set_testdata__MRBForwardingResourceResponse_Item( SI_E1AP_DT_MRBForwardingResourceResponse_Item ** pMRBForwardingResourceResponse_Item);
void __si_e1ap__set_testdata__MCForwardingResourceRelease( SI_E1AP_DT_MCForwardingResourceRelease ** pMCForwardingResourceRelease);
void __si_e1ap__set_testdata__MCForwardingResourceReleaseIndication( SI_E1AP_DT_MCForwardingResourceReleaseIndication ** pMCForwardingResourceReleaseIndication);
void __si_e1ap__set_testdata__MRB_ProgressInformation( SI_E1AP_DT_MRB_ProgressInformation ** pMRB_ProgressInformation);
void __si_e1ap__set_testdata__MRB_ProgressInformationSNs( SI_E1AP_DT_MRB_ProgressInformationSNs ** pMRB_ProgressInformationSNs);
void __si_e1ap__set_testdata__MRDC_Data_Usage_Report_Item( SI_E1AP_DT_MRDC_Data_Usage_Report_Item ** pMRDC_Data_Usage_Report_Item);
void __si_e1ap__set_testdata__MRDC_Usage_Information( SI_E1AP_DT_MRDC_Usage_Information ** pMRDC_Usage_Information);
void __si_e1ap__set_testdata__M4Configuration( SI_E1AP_DT_M4Configuration ** pM4Configuration);
void __si_e1ap__set_testdata__M6Configuration( SI_E1AP_DT_M6Configuration ** pM6Configuration);
void __si_e1ap__set_testdata__M7Configuration( SI_E1AP_DT_M7Configuration ** pM7Configuration);
void __si_e1ap__set_testdata__MDT_Configuration( SI_E1AP_DT_MDT_Configuration ** pMDT_Configuration);
void __si_e1ap__set_testdata__MDTMode( SI_E1AP_DT_MDTMode ** pMDTMode);
void __si_e1ap__set_testdata__MDTPLMNList( SI_E1AP_DT_MDTPLMNList ** pMDTPLMNList);
void __si_e1ap__set_testdata__MDTPLMNModificationList( SI_E1AP_DT_MDTPLMNModificationList ** pMDTPLMNModificationList);
void __si_e1ap__set_testdata__MT_SDT_Information( SI_E1AP_DT_MT_SDT_Information ** pMT_SDT_Information);
void __si_e1ap__set_testdata__MBS_ServiceArea( SI_E1AP_DT_MBS_ServiceArea ** pMBS_ServiceArea);
void __si_e1ap__set_testdata__MBS_ServiceAreaInformation( SI_E1AP_DT_MBS_ServiceAreaInformation ** pMBS_ServiceAreaInformation);
void __si_e1ap__set_testdata__MBS_ServiceAreaCellList( SI_E1AP_DT_MBS_ServiceAreaCellList ** pMBS_ServiceAreaCellList);
void __si_e1ap__set_testdata__MBS_ServiceAreaTAIList( SI_E1AP_DT_MBS_ServiceAreaTAIList ** pMBS_ServiceAreaTAIList);
void __si_e1ap__set_testdata__MBS_ServiceAreaTAIList_Item( SI_E1AP_DT_MBS_ServiceAreaTAIList_Item ** pMBS_ServiceAreaTAIList_Item);
void __si_e1ap__set_testdata__MBS_ServiceAreaInformationList( SI_E1AP_DT_MBS_ServiceAreaInformationList ** pMBS_ServiceAreaInformationList);
void __si_e1ap__set_testdata__MBS_ServiceAreaInformationItem( SI_E1AP_DT_MBS_ServiceAreaInformationItem ** pMBS_ServiceAreaInformationItem);
void __si_e1ap__set_testdata__NGRANAllocationAndRetentionPriority( SI_E1AP_DT_NGRANAllocationAndRetentionPriority ** pNGRANAllocationAndRetentionPriority);
void __si_e1ap__set_testdata__NG_RAN_QoS_Support_List( SI_E1AP_DT_NG_RAN_QoS_Support_List ** pNG_RAN_QoS_Support_List);
void __si_e1ap__set_testdata__NG_RAN_QoS_Support_Item( SI_E1AP_DT_NG_RAN_QoS_Support_Item ** pNG_RAN_QoS_Support_Item);
void __si_e1ap__set_testdata__Non_Dynamic5QIDescriptor( SI_E1AP_DT_Non_Dynamic5QIDescriptor ** pNon_Dynamic5QIDescriptor);
void __si_e1ap__set_testdata__NPNSupportInfo( SI_E1AP_DT_NPNSupportInfo ** pNPNSupportInfo);
void __si_e1ap__set_testdata__NPNSupportInfo_SNPN( SI_E1AP_DT_NPNSupportInfo_SNPN ** pNPNSupportInfo_SNPN);
void __si_e1ap__set_testdata__NPNContextInfo( SI_E1AP_DT_NPNContextInfo ** pNPNContextInfo);
void __si_e1ap__set_testdata__NPNContextInfo_SNPN( SI_E1AP_DT_NPNContextInfo_SNPN ** pNPNContextInfo_SNPN);
void __si_e1ap__set_testdata__NR_CGI( SI_E1AP_DT_NR_CGI ** pNR_CGI);
void __si_e1ap__set_testdata__NR_CGI_Support_List( SI_E1AP_DT_NR_CGI_Support_List ** pNR_CGI_Support_List);
void __si_e1ap__set_testdata__NR_CGI_Support_Item( SI_E1AP_DT_NR_CGI_Support_Item ** pNR_CGI_Support_Item);
void __si_e1ap__set_testdata__Extended_NR_CGI_Support_List( SI_E1AP_DT_Extended_NR_CGI_Support_List ** pExtended_NR_CGI_Support_List);
void __si_e1ap__set_testdata__Extended_NR_CGI_Support_Item( SI_E1AP_DT_Extended_NR_CGI_Support_Item ** pExtended_NR_CGI_Support_Item);
void __si_e1ap__set_testdata__N6JitterInformation( SI_E1AP_DT_N6JitterInformation ** pN6JitterInformation);
void __si_e1ap__set_testdata__PacketErrorRate( SI_E1AP_DT_PacketErrorRate ** pPacketErrorRate);
void __si_e1ap__set_testdata__PDCP_Configuration( SI_E1AP_DT_PDCP_Configuration ** pPDCP_Configuration);
void __si_e1ap__set_testdata__PDCP_Count( SI_E1AP_DT_PDCP_Count ** pPDCP_Count);
void __si_e1ap__set_testdata__PDU_Session_Resource_Data_Usage_List( SI_E1AP_DT_PDU_Session_Resource_Data_Usage_List ** pPDU_Session_Resource_Data_Usage_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Data_Usage_Item( SI_E1AP_DT_PDU_Session_Resource_Data_Usage_Item ** pPDU_Session_Resource_Data_Usage_Item);
void __si_e1ap__set_testdata__PDCP_SN_Status_Information( SI_E1AP_DT_PDCP_SN_Status_Information ** pPDCP_SN_Status_Information);
void __si_e1ap__set_testdata__DRBBStatusTransfer( SI_E1AP_DT_DRBBStatusTransfer ** pDRBBStatusTransfer);
void __si_e1ap__set_testdata__PDU_Session_Resource_Activity_List( SI_E1AP_DT_PDU_Session_Resource_Activity_List ** pPDU_Session_Resource_Activity_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Activity_Item( SI_E1AP_DT_PDU_Session_Resource_Activity_Item ** pPDU_Session_Resource_Activity_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_Confirm_Modified_List( SI_E1AP_DT_PDU_Session_Resource_Confirm_Modified_List ** pPDU_Session_Resource_Confirm_Modified_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Confirm_Modified_Item( SI_E1AP_DT_PDU_Session_Resource_Confirm_Modified_Item ** pPDU_Session_Resource_Confirm_Modified_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_Failed_List( SI_E1AP_DT_PDU_Session_Resource_Failed_List ** pPDU_Session_Resource_Failed_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Failed_Item( SI_E1AP_DT_PDU_Session_Resource_Failed_Item ** pPDU_Session_Resource_Failed_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_Failed_Mod_List( SI_E1AP_DT_PDU_Session_Resource_Failed_Mod_List ** pPDU_Session_Resource_Failed_Mod_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Failed_Mod_Item( SI_E1AP_DT_PDU_Session_Resource_Failed_Mod_Item ** pPDU_Session_Resource_Failed_Mod_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_Failed_To_Modify_List( SI_E1AP_DT_PDU_Session_Resource_Failed_To_Modify_List ** pPDU_Session_Resource_Failed_To_Modify_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Failed_To_Modify_Item( SI_E1AP_DT_PDU_Session_Resource_Failed_To_Modify_Item ** pPDU_Session_Resource_Failed_To_Modify_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_Modified_List( SI_E1AP_DT_PDU_Session_Resource_Modified_List ** pPDU_Session_Resource_Modified_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Modified_Item( SI_E1AP_DT_PDU_Session_Resource_Modified_Item ** pPDU_Session_Resource_Modified_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_Required_To_Modify_List( SI_E1AP_DT_PDU_Session_Resource_Required_To_Modify_List ** pPDU_Session_Resource_Required_To_Modify_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Required_To_Modify_Item( SI_E1AP_DT_PDU_Session_Resource_Required_To_Modify_Item ** pPDU_Session_Resource_Required_To_Modify_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_Setup_List( SI_E1AP_DT_PDU_Session_Resource_Setup_List ** pPDU_Session_Resource_Setup_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Setup_Item( SI_E1AP_DT_PDU_Session_Resource_Setup_Item ** pPDU_Session_Resource_Setup_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_Setup_Mod_List( SI_E1AP_DT_PDU_Session_Resource_Setup_Mod_List ** pPDU_Session_Resource_Setup_Mod_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_Setup_Mod_Item( SI_E1AP_DT_PDU_Session_Resource_Setup_Mod_Item ** pPDU_Session_Resource_Setup_Mod_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_To_Modify_List( SI_E1AP_DT_PDU_Session_Resource_To_Modify_List ** pPDU_Session_Resource_To_Modify_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_To_Modify_Item( SI_E1AP_DT_PDU_Session_Resource_To_Modify_Item ** pPDU_Session_Resource_To_Modify_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_To_Remove_List( SI_E1AP_DT_PDU_Session_Resource_To_Remove_List ** pPDU_Session_Resource_To_Remove_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_To_Remove_Item( SI_E1AP_DT_PDU_Session_Resource_To_Remove_Item ** pPDU_Session_Resource_To_Remove_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_To_Setup_List( SI_E1AP_DT_PDU_Session_Resource_To_Setup_List ** pPDU_Session_Resource_To_Setup_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_To_Setup_Item( SI_E1AP_DT_PDU_Session_Resource_To_Setup_Item ** pPDU_Session_Resource_To_Setup_Item);
void __si_e1ap__set_testdata__PDU_Session_Resource_To_Setup_Mod_List( SI_E1AP_DT_PDU_Session_Resource_To_Setup_Mod_List ** pPDU_Session_Resource_To_Setup_Mod_List);
void __si_e1ap__set_testdata__PDU_Session_Resource_To_Setup_Mod_Item( SI_E1AP_DT_PDU_Session_Resource_To_Setup_Mod_Item ** pPDU_Session_Resource_To_Setup_Mod_Item);
void __si_e1ap__set_testdata__PDU_Session_To_Notify_List( SI_E1AP_DT_PDU_Session_To_Notify_List ** pPDU_Session_To_Notify_List);
void __si_e1ap__set_testdata__PDU_Session_To_Notify_Item( SI_E1AP_DT_PDU_Session_To_Notify_Item ** pPDU_Session_To_Notify_Item);
void __si_e1ap__set_testdata__PDUSetQoSParameters( SI_E1AP_DT_PDUSetQoSParameters ** pPDUSetQoSParameters);
void __si_e1ap__set_testdata__PDUSetQoSInformation( SI_E1AP_DT_PDUSetQoSInformation ** pPDUSetQoSInformation);
void __si_e1ap__set_testdata__QoS_Characteristics( SI_E1AP_DT_QoS_Characteristics ** pQoS_Characteristics);
void __si_e1ap__set_testdata__QoS_Flow_List( SI_E1AP_DT_QoS_Flow_List ** pQoS_Flow_List);
void __si_e1ap__set_testdata__QoS_Flow_Item( SI_E1AP_DT_QoS_Flow_Item ** pQoS_Flow_Item);
void __si_e1ap__set_testdata__QoS_Flow_Failed_List( SI_E1AP_DT_QoS_Flow_Failed_List ** pQoS_Flow_Failed_List);
void __si_e1ap__set_testdata__QoS_Flow_Failed_Item( SI_E1AP_DT_QoS_Flow_Failed_Item ** pQoS_Flow_Failed_Item);
void __si_e1ap__set_testdata__QoS_Flow_Mapping_List( SI_E1AP_DT_QoS_Flow_Mapping_List ** pQoS_Flow_Mapping_List);
void __si_e1ap__set_testdata__QoS_Flow_Mapping_Item( SI_E1AP_DT_QoS_Flow_Mapping_Item ** pQoS_Flow_Mapping_Item);
void __si_e1ap__set_testdata__QoS_Parameters_Support_List( SI_E1AP_DT_QoS_Parameters_Support_List ** pQoS_Parameters_Support_List);
void __si_e1ap__set_testdata__QoS_Flow_QoS_Parameter_List( SI_E1AP_DT_QoS_Flow_QoS_Parameter_List ** pQoS_Flow_QoS_Parameter_List);
void __si_e1ap__set_testdata__QoS_Flow_QoS_Parameter_Item( SI_E1AP_DT_QoS_Flow_QoS_Parameter_Item ** pQoS_Flow_QoS_Parameter_Item);
void __si_e1ap__set_testdata__QoSFlowLevelQoSParameters( SI_E1AP_DT_QoSFlowLevelQoSParameters ** pQoSFlowLevelQoSParameters);
void __si_e1ap__set_testdata__QoS_Flow_Removed_Item( SI_E1AP_DT_QoS_Flow_Removed_Item ** pQoS_Flow_Removed_Item);
void __si_e1ap__set_testdata__QoS_Flows_to_be_forwarded_List( SI_E1AP_DT_QoS_Flows_to_be_forwarded_List ** pQoS_Flows_to_be_forwarded_List);
void __si_e1ap__set_testdata__QoS_Flows_to_be_forwarded_Item( SI_E1AP_DT_QoS_Flows_to_be_forwarded_Item ** pQoS_Flows_to_be_forwarded_Item);
void __si_e1ap__set_testdata__QoS_Mapping_Information( SI_E1AP_DT_QoS_Mapping_Information ** pQoS_Mapping_Information);
void __si_e1ap__set_testdata__DataForwardingtoNG_RANQoSFlowInformationList( SI_E1AP_DT_DataForwardingtoNG_RANQoSFlowInformationList ** pDataForwardingtoNG_RANQoSFlowInformationList);
void __si_e1ap__set_testdata__DataForwardingtoNG_RANQoSFlowInformationList_Item( SI_E1AP_DT_DataForwardingtoNG_RANQoSFlowInformationList_Item ** pDataForwardingtoNG_RANQoSFlowInformationList_Item);
void __si_e1ap__set_testdata__RedundantPDUSessionInformation( SI_E1AP_DT_RedundantPDUSessionInformation ** pRedundantPDUSessionInformation);
void __si_e1ap__set_testdata__RetainabilityMeasurementsInfo( SI_E1AP_DT_RetainabilityMeasurementsInfo ** pRetainabilityMeasurementsInfo);
void __si_e1ap__set_testdata__ROHC_Parameters( SI_E1AP_DT_ROHC_Parameters ** pROHC_Parameters);
void __si_e1ap__set_testdata__ROHC( SI_E1AP_DT_ROHC ** pROHC);
void __si_e1ap__set_testdata__SecurityAlgorithm( SI_E1AP_DT_SecurityAlgorithm ** pSecurityAlgorithm);
void __si_e1ap__set_testdata__SecurityIndication( SI_E1AP_DT_SecurityIndication ** pSecurityIndication);
void __si_e1ap__set_testdata__SecurityInformation( SI_E1AP_DT_SecurityInformation ** pSecurityInformation);
void __si_e1ap__set_testdata__SecurityResult( SI_E1AP_DT_SecurityResult ** pSecurityResult);
void __si_e1ap__set_testdata__Slice_Support_List( SI_E1AP_DT_Slice_Support_List ** pSlice_Support_List);
void __si_e1ap__set_testdata__Slice_Support_Item( SI_E1AP_DT_Slice_Support_Item ** pSlice_Support_Item);
void __si_e1ap__set_testdata__SNSSAI( SI_E1AP_DT_SNSSAI ** pSNSSAI);
void __si_e1ap__set_testdata__SDAP_Configuration( SI_E1AP_DT_SDAP_Configuration ** pSDAP_Configuration);
void __si_e1ap__set_testdata__TNL_AvailableCapacityIndicator( SI_E1AP_DT_TNL_AvailableCapacityIndicator ** pTNL_AvailableCapacityIndicator);
void __si_e1ap__set_testdata__TSCTrafficCharacteristics( SI_E1AP_DT_TSCTrafficCharacteristics ** pTSCTrafficCharacteristics);
void __si_e1ap__set_testdata__TSCAssistanceInformation( SI_E1AP_DT_TSCAssistanceInformation ** pTSCAssistanceInformation);
void __si_e1ap__set_testdata__TraceActivation( SI_E1AP_DT_TraceActivation ** pTraceActivation);
void __si_e1ap__set_testdata__T_ReorderingTimer( SI_E1AP_DT_T_ReorderingTimer ** pT_ReorderingTimer);
void __si_e1ap__set_testdata__Transport_Layer_Address_Info( SI_E1AP_DT_Transport_Layer_Address_Info ** pTransport_Layer_Address_Info);
void __si_e1ap__set_testdata__Transport_UP_Layer_Addresses_Info_To_Add_List( SI_E1AP_DT_Transport_UP_Layer_Addresses_Info_To_Add_List ** pTransport_UP_Layer_Addresses_Info_To_Add_List);
void __si_e1ap__set_testdata__Transport_UP_Layer_Addresses_Info_To_Add_Item( SI_E1AP_DT_Transport_UP_Layer_Addresses_Info_To_Add_Item ** pTransport_UP_Layer_Addresses_Info_To_Add_Item);
void __si_e1ap__set_testdata__Transport_UP_Layer_Addresses_Info_To_Remove_List( SI_E1AP_DT_Transport_UP_Layer_Addresses_Info_To_Remove_List ** pTransport_UP_Layer_Addresses_Info_To_Remove_List);
void __si_e1ap__set_testdata__Transport_UP_Layer_Addresses_Info_To_Remove_Item( SI_E1AP_DT_Transport_UP_Layer_Addresses_Info_To_Remove_Item ** pTransport_UP_Layer_Addresses_Info_To_Remove_Item);
void __si_e1ap__set_testdata__UDC_Parameters( SI_E1AP_DT_UDC_Parameters ** pUDC_Parameters);
void __si_e1ap__set_testdata__UE_associatedLogicalE1_ConnectionItem( SI_E1AP_DT_UE_associatedLogicalE1_ConnectionItem ** pUE_associatedLogicalE1_ConnectionItem);
void __si_e1ap__set_testdata__UESliceMaximumBitRateList( SI_E1AP_DT_UESliceMaximumBitRateList ** pUESliceMaximumBitRateList);
void __si_e1ap__set_testdata__UESliceMaximumBitRateItem( SI_E1AP_DT_UESliceMaximumBitRateItem ** pUESliceMaximumBitRateItem);
void __si_e1ap__set_testdata__ULUPTNLAddressToUpdateItem( SI_E1AP_DT_ULUPTNLAddressToUpdateItem ** pULUPTNLAddressToUpdateItem);
void __si_e1ap__set_testdata__UP_Parameters( SI_E1AP_DT_UP_Parameters ** pUP_Parameters);
void __si_e1ap__set_testdata__UP_Parameters_Item( SI_E1AP_DT_UP_Parameters_Item ** pUP_Parameters_Item);
void __si_e1ap__set_testdata__UPSecuritykey( SI_E1AP_DT_UPSecuritykey ** pUPSecuritykey);
void __si_e1ap__set_testdata__UP_TNL_Information( SI_E1AP_DT_UP_TNL_Information ** pUP_TNL_Information);
void __si_e1ap__set_testdata__UplinkOnlyROHC( SI_E1AP_DT_UplinkOnlyROHC ** pUplinkOnlyROHC);
void __si_e1ap__set_testdata__UserPlaneFailureIndication( SI_E1AP_DT_UserPlaneFailureIndication ** pUserPlaneFailureIndication);
void __si_e1ap__set_testdata__ResetType( SI_E1AP_DT_ResetType ** pResetType);
void __si_e1ap__set_testdata__System_BearerContextSetupRequest( SI_E1AP_DT_System_BearerContextSetupRequest ** pSystem_BearerContextSetupRequest);
void __si_e1ap__set_testdata__System_BearerContextSetupResponse( SI_E1AP_DT_System_BearerContextSetupResponse ** pSystem_BearerContextSetupResponse);
void __si_e1ap__set_testdata__System_BearerContextModificationRequest( SI_E1AP_DT_System_BearerContextModificationRequest ** pSystem_BearerContextModificationRequest);
void __si_e1ap__set_testdata__System_BearerContextModificationResponse( SI_E1AP_DT_System_BearerContextModificationResponse ** pSystem_BearerContextModificationResponse);
void __si_e1ap__set_testdata__System_BearerContextModificationRequired( SI_E1AP_DT_System_BearerContextModificationRequired ** pSystem_BearerContextModificationRequired);
void __si_e1ap__set_testdata__System_BearerContextModificationConfirm( SI_E1AP_DT_System_BearerContextModificationConfirm ** pSystem_BearerContextModificationConfirm);
void __si_e1ap__set_testdata__System_GNB_CU_UP_CounterCheckRequest( SI_E1AP_DT_System_GNB_CU_UP_CounterCheckRequest ** pSystem_GNB_CU_UP_CounterCheckRequest);
void __si_e1ap__set_testdata__UE_associatedLogicalE1_ConnectionListRes( SI_E1AP_DT_UE_associatedLogicalE1_ConnectionListRes ** pUE_associatedLogicalE1_ConnectionListRes);
void __si_e1ap__set_testdata__UE_associatedLogicalE1_ConnectionListResAck( SI_E1AP_DT_UE_associatedLogicalE1_ConnectionListResAck ** pUE_associatedLogicalE1_ConnectionListResAck);
void __si_e1ap__set_testdata__SupportedPLMNs_List( SI_E1AP_DT_SupportedPLMNs_List ** pSupportedPLMNs_List);
void __si_e1ap__set_testdata__SupportedPLMNs_Item( SI_E1AP_DT_SupportedPLMNs_Item ** pSupportedPLMNs_Item);
void __si_e1ap__set_testdata__GNB_CU_UP_TNLA_To_Remove_List( SI_E1AP_DT_GNB_CU_UP_TNLA_To_Remove_List ** pGNB_CU_UP_TNLA_To_Remove_List);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_To_Add_List( SI_E1AP_DT_GNB_CU_CP_TNLA_To_Add_List ** pGNB_CU_CP_TNLA_To_Add_List);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_To_Remove_List( SI_E1AP_DT_GNB_CU_CP_TNLA_To_Remove_List ** pGNB_CU_CP_TNLA_To_Remove_List);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_To_Update_List( SI_E1AP_DT_GNB_CU_CP_TNLA_To_Update_List ** pGNB_CU_CP_TNLA_To_Update_List);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_Setup_List( SI_E1AP_DT_GNB_CU_CP_TNLA_Setup_List ** pGNB_CU_CP_TNLA_Setup_List);
void __si_e1ap__set_testdata__GNB_CU_CP_TNLA_Failed_To_Setup_List( SI_E1AP_DT_GNB_CU_CP_TNLA_Failed_To_Setup_List ** pGNB_CU_CP_TNLA_Failed_To_Setup_List);
void __si_e1ap__set_testdata__DRB_Status_List( SI_E1AP_DT_DRB_Status_List ** pDRB_Status_List);
void __si_e1ap__set_testdata__DLUPTNLAddressToUpdateList( SI_E1AP_DT_DLUPTNLAddressToUpdateList ** pDLUPTNLAddressToUpdateList);
void __si_e1ap__set_testdata__ULUPTNLAddressToUpdateList( SI_E1AP_DT_ULUPTNLAddressToUpdateList ** pULUPTNLAddressToUpdateList);
void __si_e1ap__set_testdata__IAB_Donor_CU_UPPSKInfo( SI_E1AP_DT_IAB_Donor_CU_UPPSKInfo ** pIAB_Donor_CU_UPPSKInfo);


void __si_e1ap__set_testdata__PDU_ActivityInformation_ExtIEs( SI_E1AP_DT_PDU_ActivityInformation_ExtIEs ** pActivityInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_AlternativeQoSParaSetItem_ExtIEs( SI_E1AP_DT_PDU_AlternativeQoSParaSetItem_ExtIEs ** pAlternativeQoSParaSetItem_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextToSetup_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextToSetup_ExtIEs ** pBCBearerContextToSetup_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextNGU_TNLInfoat5GC_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextNGU_TNLInfoat5GC_ExtIEs ** pBCBearerContextNGU_TNLInfoat5GC_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCMRBSetupConfiguration_Item_ExtIEs( SI_E1AP_DT_PDU_BCMRBSetupConfiguration_Item_ExtIEs ** pBCMRBSetupConfiguration_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextToSetupResponse_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextToSetupResponse_ExtIEs ** pBCBearerContextToSetupResponse_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextNGU_TNLInfoatNGRAN_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextNGU_TNLInfoatNGRAN_ExtIEs ** pBCBearerContextNGU_TNLInfoatNGRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCMRBSetupResponseList_Item_ExtIEs( SI_E1AP_DT_PDU_BCMRBSetupResponseList_Item_ExtIEs ** pBCMRBSetupResponseList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextF1U_TNLInfoatCU_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextF1U_TNLInfoatCU_ExtIEs ** pBCBearerContextF1U_TNLInfoatCU_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCMRBFailedList_Item_ExtIEs( SI_E1AP_DT_PDU_BCMRBFailedList_Item_ExtIEs ** pBCMRBFailedList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextToModify_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextToModify_ExtIEs ** pBCBearerContextToModify_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextNGU_TNLInfoatNGRAN_Request_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextNGU_TNLInfoatNGRAN_Request_ExtIEs ** pBCBearerContextNGU_TNLInfoatNGRAN_Request_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCMRBModifyConfiguration_Item_ExtIEs( SI_E1AP_DT_PDU_BCMRBModifyConfiguration_Item_ExtIEs ** pBCMRBModifyConfiguration_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextF1U_TNLInfoatDU_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextF1U_TNLInfoatDU_ExtIEs ** pBCBearerContextF1U_TNLInfoatDU_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextToModifyResponse_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextToModifyResponse_ExtIEs ** pBCBearerContextToModifyResponse_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCMRBSetupModifyResponseList_Item_ExtIEs( SI_E1AP_DT_PDU_BCMRBSetupModifyResponseList_Item_ExtIEs ** pBCMRBSetupModifyResponseList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextToModifyRequired_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextToModifyRequired_ExtIEs ** pBCBearerContextToModifyRequired_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_BCBearerContextToModifyConfirm_ExtIEs( SI_E1AP_DT_PDU_BCBearerContextToModifyConfirm_ExtIEs ** pBCBearerContextToModifyConfirm_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Cause_ExtIEs( SI_E1AP_DT_PDU_Cause_ExtIEs ** pCause_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Cell_Group_Information_Item_ExtIEs( SI_E1AP_DT_PDU_Cell_Group_Information_Item_ExtIEs ** pCell_Group_Information_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_CP_TNL_Information_ExtIEs( SI_E1AP_DT_PDU_CP_TNL_Information_ExtIEs ** pCP_TNL_Information_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_CriticalityDiagnostics_ExtIEs( SI_E1AP_DT_PDU_CriticalityDiagnostics_ExtIEs ** pCriticalityDiagnostics_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_CriticalityDiagnostics_IE_List_ExtIEs( SI_E1AP_DT_PDU_CriticalityDiagnostics_IE_List_ExtIEs ** pCriticalityDiagnostics_IE_List_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DAPSRequestInfo_ExtIEs( SI_E1AP_DT_PDU_DAPSRequestInfo_ExtIEs ** pDAPSRequestInfo_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Data_Forwarding_Information_Request_ExtIEs( SI_E1AP_DT_PDU_Data_Forwarding_Information_Request_ExtIEs ** pData_Forwarding_Information_Request_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Data_Forwarding_Information_ExtIEs( SI_E1AP_DT_PDU_Data_Forwarding_Information_ExtIEs ** pData_Forwarding_Information_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DataForwardingtoE_UTRANInformationListItem_ExtIEs( SI_E1AP_DT_PDU_DataForwardingtoE_UTRANInformationListItem_ExtIEs ** pDataForwardingtoE_UTRANInformationListItem_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Data_Usage_per_PDU_Session_Report_ExtIEs( SI_E1AP_DT_PDU_Data_Usage_per_PDU_Session_Report_ExtIEs ** pData_Usage_per_PDU_Session_Report_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Data_Usage_per_QoS_Flow_Item_ExtIEs( SI_E1AP_DT_PDU_Data_Usage_per_QoS_Flow_Item_ExtIEs ** pData_Usage_per_QoS_Flow_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Data_Usage_Report_ItemExtIEs( SI_E1AP_DT_PDU_Data_Usage_Report_ItemExtIEs ** pData_Usage_Report_ItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DLDiscarding_ExtIEs( SI_E1AP_DT_PDU_DLDiscarding_ExtIEs ** pDLDiscarding_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DLUPTNLAddressToUpdateItemExtIEs( SI_E1AP_DT_PDU_DLUPTNLAddressToUpdateItemExtIEs ** pDLUPTNLAddressToUpdateItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Activity_ItemExtIEs( SI_E1AP_DT_PDU_DRB_Activity_ItemExtIEs ** pDRB_Activity_ItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Confirm_Modified_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Confirm_Modified_Item_EUTRAN_ExtIEs ** pDRB_Confirm_Modified_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Confirm_Modified_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Confirm_Modified_Item_NG_RAN_ExtIEs ** pDRB_Confirm_Modified_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Failed_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Failed_Item_EUTRAN_ExtIEs ** pDRB_Failed_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Failed_Mod_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Failed_Mod_Item_EUTRAN_ExtIEs ** pDRB_Failed_Mod_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Failed_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Failed_Item_NG_RAN_ExtIEs ** pDRB_Failed_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Failed_Mod_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Failed_Mod_Item_NG_RAN_ExtIEs ** pDRB_Failed_Mod_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Failed_To_Modify_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Failed_To_Modify_Item_EUTRAN_ExtIEs ** pDRB_Failed_To_Modify_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Failed_To_Modify_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Failed_To_Modify_Item_NG_RAN_ExtIEs ** pDRB_Failed_To_Modify_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Measurement_Results_Information_Item_ExtIEs( SI_E1AP_DT_PDU_DRB_Measurement_Results_Information_Item_ExtIEs ** pDRB_Measurement_Results_Information_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Modified_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Modified_Item_EUTRAN_ExtIEs ** pDRB_Modified_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Modified_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Modified_Item_NG_RAN_ExtIEs ** pDRB_Modified_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Removed_Item_ExtIEs( SI_E1AP_DT_PDU_DRB_Removed_Item_ExtIEs ** pDRB_Removed_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Required_To_Modify_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Required_To_Modify_Item_EUTRAN_ExtIEs ** pDRB_Required_To_Modify_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Required_To_Modify_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Required_To_Modify_Item_NG_RAN_ExtIEs ** pDRB_Required_To_Modify_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Setup_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Setup_Item_EUTRAN_ExtIEs ** pDRB_Setup_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Setup_Mod_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Setup_Mod_Item_EUTRAN_ExtIEs ** pDRB_Setup_Mod_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Setup_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Setup_Item_NG_RAN_ExtIEs ** pDRB_Setup_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Setup_Mod_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Setup_Mod_Item_NG_RAN_ExtIEs ** pDRB_Setup_Mod_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Status_ItemExtIEs( SI_E1AP_DT_PDU_DRB_Status_ItemExtIEs ** pDRB_Status_ItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRBs_Subject_To_Counter_Check_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRBs_Subject_To_Counter_Check_Item_EUTRAN_ExtIEs ** pDRBs_Subject_To_Counter_Check_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRBs_Subject_To_Counter_Check_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRBs_Subject_To_Counter_Check_Item_NG_RAN_ExtIEs ** pDRBs_Subject_To_Counter_Check_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRBs_Subject_To_Early_Forwarding_Item_ExtIEs( SI_E1AP_DT_PDU_DRBs_Subject_To_Early_Forwarding_Item_ExtIEs ** pDRBs_Subject_To_Early_Forwarding_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_To_Modify_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_To_Modify_Item_EUTRAN_ExtIEs ** pDRB_To_Modify_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_To_Modify_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_To_Modify_Item_NG_RAN_ExtIEs ** pDRB_To_Modify_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_To_Remove_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_To_Remove_Item_EUTRAN_ExtIEs ** pDRB_To_Remove_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Required_To_Remove_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Required_To_Remove_Item_EUTRAN_ExtIEs ** pDRB_Required_To_Remove_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_To_Remove_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_To_Remove_Item_NG_RAN_ExtIEs ** pDRB_To_Remove_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Required_To_Remove_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_Required_To_Remove_Item_NG_RAN_ExtIEs ** pDRB_Required_To_Remove_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_To_Setup_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_To_Setup_Item_EUTRAN_ExtIEs ** pDRB_To_Setup_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_To_Setup_Mod_Item_EUTRAN_ExtIEs( SI_E1AP_DT_PDU_DRB_To_Setup_Mod_Item_EUTRAN_ExtIEs ** pDRB_To_Setup_Mod_Item_EUTRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_To_Setup_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_To_Setup_Item_NG_RAN_ExtIEs ** pDRB_To_Setup_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_To_Setup_Mod_Item_NG_RAN_ExtIEs( SI_E1AP_DT_PDU_DRB_To_Setup_Mod_Item_NG_RAN_ExtIEs ** pDRB_To_Setup_Mod_Item_NG_RAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRB_Usage_Report_Item_ExtIEs( SI_E1AP_DT_PDU_DRB_Usage_Report_Item_ExtIEs ** pDRB_Usage_Report_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Dynamic5QIDescriptor_ExtIEs( SI_E1AP_DT_PDU_Dynamic5QIDescriptor_ExtIEs ** pDynamic5QIDescriptor_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EarlyForwardingCOUNTInfo_ExtIEs( SI_E1AP_DT_PDU_EarlyForwardingCOUNTInfo_ExtIEs ** pEarlyForwardingCOUNTInfo_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_ECNMarkingorCongestionInformationReportingRequest_ExtIEs( SI_E1AP_DT_PDU_ECNMarkingorCongestionInformationReportingRequest_ExtIEs ** pECNMarkingorCongestionInformationReportingRequest_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EHC_Common_Parameters_ExtIEs( SI_E1AP_DT_PDU_EHC_Common_Parameters_ExtIEs ** pEHC_Common_Parameters_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EHC_Downlink_Parameters_ExtIEs( SI_E1AP_DT_PDU_EHC_Downlink_Parameters_ExtIEs ** pEHC_Downlink_Parameters_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EHC_Uplink_Parameters_ExtIEs( SI_E1AP_DT_PDU_EHC_Uplink_Parameters_ExtIEs ** pEHC_Uplink_Parameters_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EHC_Parameters_ExtIEs( SI_E1AP_DT_PDU_EHC_Parameters_ExtIEs ** pEHC_Parameters_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Endpoint_IP_address_and_port_ExtIEs( SI_E1AP_DT_PDU_Endpoint_IP_address_and_port_ExtIEs ** pEndpoint_IP_address_and_port_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRANAllocationAndRetentionPriority_ExtIEs( SI_E1AP_DT_PDU_EUTRANAllocationAndRetentionPriority_ExtIEs ** pEUTRANAllocationAndRetentionPriority_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_ECGI_ExtIEs( SI_E1AP_DT_PDU_ECGI_ExtIEs ** pECGI_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_ECGI_Support_Item_ExtIEs( SI_E1AP_DT_PDU_ECGI_Support_Item_ExtIEs ** pECGI_Support_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_QoS_Support_Item_ExtIEs( SI_E1AP_DT_PDU_EUTRAN_QoS_Support_Item_ExtIEs ** pEUTRAN_QoS_Support_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_QoS_ExtIEs( SI_E1AP_DT_PDU_EUTRAN_QoS_ExtIEs ** pEUTRAN_QoS_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_FirstDLCount_ExtIEs( SI_E1AP_DT_PDU_FirstDLCount_ExtIEs ** pFirstDLCount_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_F1U_TNL_InfoAdded_Item_ExtIEs( SI_E1AP_DT_PDU_F1U_TNL_InfoAdded_Item_ExtIEs ** pF1U_TNL_InfoAdded_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_F1U_TNL_InfoToAdd_Item_ExtIEs( SI_E1AP_DT_PDU_F1U_TNL_InfoToAdd_Item_ExtIEs ** pF1U_TNL_InfoToAdd_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_F1U_TNL_InfoAddedOrModified_Item_ExtIEs( SI_E1AP_DT_PDU_F1U_TNL_InfoAddedOrModified_Item_ExtIEs ** pF1U_TNL_InfoAddedOrModified_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_F1U_TNL_InfoToAddOrModify_Item_ExtIEs( SI_E1AP_DT_PDU_F1U_TNL_InfoToAddOrModify_Item_ExtIEs ** pF1U_TNL_InfoToAddOrModify_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_F1U_TNL_InfoToRelease_Item_ExtIEs( SI_E1AP_DT_PDU_F1U_TNL_InfoToRelease_Item_ExtIEs ** pF1U_TNL_InfoToRelease_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GlobalMBSSessionID_ExtIEs( SI_E1AP_DT_PDU_GlobalMBSSessionID_ExtIEs ** pGlobalMBSSessionID_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Extended_GNB_CU_CP_Name_ExtIEs( SI_E1AP_DT_PDU_Extended_GNB_CU_CP_Name_ExtIEs ** pExtended_GNB_CU_CP_Name_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GNB_CU_UP_CellGroupRelatedConfiguration_Item_ExtIEs( SI_E1AP_DT_PDU_GNB_CU_UP_CellGroupRelatedConfiguration_Item_ExtIEs ** pGNB_CU_UP_CellGroupRelatedConfiguration_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GNB_CU_UP_MBS_Support_Info_ExtIEs( SI_E1AP_DT_PDU_GNB_CU_UP_MBS_Support_Info_ExtIEs ** pGNB_CU_UP_MBS_Support_Info_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Extended_GNB_CU_UP_Name_ExtIEs( SI_E1AP_DT_PDU_Extended_GNB_CU_UP_Name_ExtIEs ** pExtended_GNB_CU_UP_Name_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GNB_CU_CP_TNLA_Setup_Item_ExtIEs( SI_E1AP_DT_PDU_GNB_CU_CP_TNLA_Setup_Item_ExtIEs ** pGNB_CU_CP_TNLA_Setup_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GNB_CU_CP_TNLA_Failed_To_Setup_Item_ExtIEs( SI_E1AP_DT_PDU_GNB_CU_CP_TNLA_Failed_To_Setup_Item_ExtIEs ** pGNB_CU_CP_TNLA_Failed_To_Setup_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GNB_CU_CP_TNLA_To_Add_Item_ExtIEs( SI_E1AP_DT_PDU_GNB_CU_CP_TNLA_To_Add_Item_ExtIEs ** pGNB_CU_CP_TNLA_To_Add_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GNB_CU_CP_TNLA_To_Remove_Item_ExtIEs( SI_E1AP_DT_PDU_GNB_CU_CP_TNLA_To_Remove_Item_ExtIEs ** pGNB_CU_CP_TNLA_To_Remove_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GNB_CU_CP_TNLA_To_Update_Item_ExtIEs( SI_E1AP_DT_PDU_GNB_CU_CP_TNLA_To_Update_Item_ExtIEs ** pGNB_CU_CP_TNLA_To_Update_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GNB_CU_UP_TNLA_To_Remove_Item_ExtIEs( SI_E1AP_DT_PDU_GNB_CU_UP_TNLA_To_Remove_Item_ExtIEs ** pGNB_CU_UP_TNLA_To_Remove_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GBR_QosInformation_ExtIEs( SI_E1AP_DT_PDU_GBR_QosInformation_ExtIEs ** pGBR_QosInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GBR_QosFlowInformation_ExtIEs( SI_E1AP_DT_PDU_GBR_QosFlowInformation_ExtIEs ** pGBR_QosFlowInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GTPTLA_Item_ExtIEs( SI_E1AP_DT_PDU_GTPTLA_Item_ExtIEs ** pGTPTLA_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_GTPTunnel_ExtIEs( SI_E1AP_DT_PDU_GTPTunnel_ExtIEs ** pGTPTunnel_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_HW_CapacityIndicator_ExtIEs( SI_E1AP_DT_PDU_HW_CapacityIndicator_ExtIEs ** pHW_CapacityIndicator_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_ImmediateMDT_ExtIEs( SI_E1AP_DT_PDU_ImmediateMDT_ExtIEs ** pImmediateMDT_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_IAB_donor_CU_UPPSKInfoItemExtIEs( SI_E1AP_DT_PDU_IAB_donor_CU_UPPSKInfoItemExtIEs ** pIAB_donor_CU_UPPSKInfoItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_LocationDependentMBSNGUInformationAt5GC_Item_ExtIEs( SI_E1AP_DT_PDU_LocationDependentMBSNGUInformationAt5GC_Item_ExtIEs ** pLocationDependentMBSNGUInformationAt5GC_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_LocationDependentMBSF1UInformationAtCU_Item_ExtIEs( SI_E1AP_DT_PDU_LocationDependentMBSF1UInformationAtCU_Item_ExtIEs ** pLocationDependentMBSF1UInformationAtCU_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_LocationDependentMBSF1UInformationAtDU_Item_ExtIEs( SI_E1AP_DT_PDU_LocationDependentMBSF1UInformationAtDU_Item_ExtIEs ** pLocationDependentMBSF1UInformationAtDU_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_LocationDependentMBSNGUInformationAtNGRAN_Item_ExtIEs( SI_E1AP_DT_PDU_LocationDependentMBSNGUInformationAtNGRAN_Item_ExtIEs ** pLocationDependentMBSNGUInformationAtNGRAN_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MaximumIPdatarate_ExtIEs( SI_E1AP_DT_PDU_MaximumIPdatarate_ExtIEs ** pMaximumIPdatarate_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSF1UInformationAtCU_ExtIEs( SI_E1AP_DT_PDU_MBSF1UInformationAtCU_ExtIEs ** pMBSF1UInformationAtCU_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSF1UInformationAtDU_ExtIEs( SI_E1AP_DT_PDU_MBSF1UInformationAtDU_ExtIEs ** pMBSF1UInformationAtDU_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSNGUInformationAt5GC_ExtIEs( SI_E1AP_DT_PDU_MBSNGUInformationAt5GC_ExtIEs ** pMBSNGUInformationAt5GC_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSNGUInformationAt5GC_Multicast_ExtIEs( SI_E1AP_DT_PDU_MBSNGUInformationAt5GC_Multicast_ExtIEs ** pMBSNGUInformationAt5GC_Multicast_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSNGUInformationAtNGRAN_ExtIEs( SI_E1AP_DT_PDU_MBSNGUInformationAtNGRAN_ExtIEs ** pMBSNGUInformationAtNGRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSNGUInformationAtNGRAN_Request_Item_ExtIEs( SI_E1AP_DT_PDU_MBSNGUInformationAtNGRAN_Request_Item_ExtIEs ** pMBSNGUInformationAtNGRAN_Request_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSSessionAssociatedInfoNonSupportToSupport_ExtIEs( SI_E1AP_DT_PDU_MBSSessionAssociatedInfoNonSupportToSupport_ExtIEs ** pMBSSessionAssociatedInfoNonSupportToSupport_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSSessionAssociatedInformation_ExtIEs( SI_E1AP_DT_PDU_MBSSessionAssociatedInformation_ExtIEs ** pMBSSessionAssociatedInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSSessionAssociatedInformation_Item_ExtIEs( SI_E1AP_DT_PDU_MBSSessionAssociatedInformation_Item_ExtIEs ** pMBSSessionAssociatedInformation_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBS_Support_Info_ToAdd_Item_ExtIEs( SI_E1AP_DT_PDU_MBS_Support_Info_ToAdd_Item_ExtIEs ** pMBS_Support_Info_ToAdd_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSSessionResourceNotification_ExtIEs( SI_E1AP_DT_PDU_MBSSessionResourceNotification_ExtIEs ** pMBSSessionResourceNotification_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBS_DL_Data_Arrival_ExtIEs( SI_E1AP_DT_PDU_MBS_DL_Data_Arrival_ExtIEs ** pMBS_DL_Data_Arrival_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContext_Inactivity_ExtIEs( SI_E1AP_DT_PDU_MCBearerContext_Inactivity_ExtIEs ** pMCBearerContext_Inactivity_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBS_Support_Info_ToRemove_Item_ExtIEs( SI_E1AP_DT_PDU_MBS_Support_Info_ToRemove_Item_ExtIEs ** pMBS_Support_Info_ToRemove_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextToSetup_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextToSetup_ExtIEs ** pMCBearerContextToSetup_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCMRBSetupConfiguration_Item_ExtIEs( SI_E1AP_DT_PDU_MCMRBSetupConfiguration_Item_ExtIEs ** pMCMRBSetupConfiguration_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextToSetupResponse_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextToSetupResponse_ExtIEs ** pMCBearerContextToSetupResponse_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextNGU_TNLInfoatNGRAN_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextNGU_TNLInfoatNGRAN_ExtIEs ** pMCBearerContextNGU_TNLInfoatNGRAN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCMRBSetupResponseList_Item_ExtIEs( SI_E1AP_DT_PDU_MCMRBSetupResponseList_Item_ExtIEs ** pMCMRBSetupResponseList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCMRBFailedList_Item_ExtIEs( SI_E1AP_DT_PDU_MCMRBFailedList_Item_ExtIEs ** pMCMRBFailedList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextToModify_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextToModify_ExtIEs ** pMCBearerContextToModify_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextNGUTNLInfoat5GC_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextNGUTNLInfoat5GC_ExtIEs ** pMCBearerContextNGUTNLInfoat5GC_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextNGUTnlInfoatNGRANRequest_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextNGUTnlInfoatNGRANRequest_ExtIEs ** pMCBearerContextNGUTnlInfoatNGRANRequest_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCMRBSetupModifyConfiguration_Item_ExtIEs( SI_E1AP_DT_PDU_MCMRBSetupModifyConfiguration_Item_ExtIEs ** pMCMRBSetupModifyConfiguration_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextF1UTNLInfoatDU_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextF1UTNLInfoatDU_ExtIEs ** pMCBearerContextF1UTNLInfoatDU_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBSMulticastF1UContextDescriptor_ExtIEs( SI_E1AP_DT_PDU_MBSMulticastF1UContextDescriptor_ExtIEs ** pMBSMulticastF1UContextDescriptor_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextToModifyResponse_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextToModifyResponse_ExtIEs ** pMCBearerContextToModifyResponse_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextNGU_TNLInfoatNGRANModifyResponse_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextNGU_TNLInfoatNGRANModifyResponse_ExtIEs ** pMCBearerContextNGU_TNLInfoatNGRANModifyResponse_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCMRBSetupModifyResponseList_Item_ExtIEs( SI_E1AP_DT_PDU_MCMRBSetupModifyResponseList_Item_ExtIEs ** pMCMRBSetupModifyResponseList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextToModifyRequired_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextToModifyRequired_ExtIEs ** pMCBearerContextToModifyRequired_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCMRBModifyRequiredConfiguration_Item_ExtIEs( SI_E1AP_DT_PDU_MCMRBModifyRequiredConfiguration_Item_ExtIEs ** pMCMRBModifyRequiredConfiguration_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCMRBModifyConfirmList_Item_ExtIEs( SI_E1AP_DT_PDU_MCMRBModifyConfirmList_Item_ExtIEs ** pMCMRBModifyConfirmList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCBearerContextToModifyConfirm_ExtIEs( SI_E1AP_DT_PDU_MCBearerContextToModifyConfirm_ExtIEs ** pMCBearerContextToModifyConfirm_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCForwardingResourceRequest_ExtIEs( SI_E1AP_DT_PDU_MCForwardingResourceRequest_ExtIEs ** pMCForwardingResourceRequest_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MRBForwardingResourceRequest_Item_ExtIEs( SI_E1AP_DT_PDU_MRBForwardingResourceRequest_Item_ExtIEs ** pMRBForwardingResourceRequest_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCForwardingResourceIndication_ExtIEs( SI_E1AP_DT_PDU_MCForwardingResourceIndication_ExtIEs ** pMCForwardingResourceIndication_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MRBForwardingResourceIndication_Item_ExtIEs( SI_E1AP_DT_PDU_MRBForwardingResourceIndication_Item_ExtIEs ** pMRBForwardingResourceIndication_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCForwardingResourceResponse_ExtIEs( SI_E1AP_DT_PDU_MCForwardingResourceResponse_ExtIEs ** pMCForwardingResourceResponse_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MRBForwardingResourceResponse_Item_ExtIEs( SI_E1AP_DT_PDU_MRBForwardingResourceResponse_Item_ExtIEs ** pMRBForwardingResourceResponse_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCForwardingResourceRelease_ExtIEs( SI_E1AP_DT_PDU_MCForwardingResourceRelease_ExtIEs ** pMCForwardingResourceRelease_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MCForwardingResourceReleaseIndication_ExtIEs( SI_E1AP_DT_PDU_MCForwardingResourceReleaseIndication_ExtIEs ** pMCForwardingResourceReleaseIndication_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MRB_ProgressInformation_ExtIEs( SI_E1AP_DT_PDU_MRB_ProgressInformation_ExtIEs ** pMRB_ProgressInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MRB_ProgressInformationSNs_ExtIEs( SI_E1AP_DT_PDU_MRB_ProgressInformationSNs_ExtIEs ** pMRB_ProgressInformationSNs_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MRDC_Data_Usage_Report_Item_ExtIEs( SI_E1AP_DT_PDU_MRDC_Data_Usage_Report_Item_ExtIEs ** pMRDC_Data_Usage_Report_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MRDC_Usage_Information_ExtIEs( SI_E1AP_DT_PDU_MRDC_Usage_Information_ExtIEs ** pMRDC_Usage_Information_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_M4Configuration_ExtIEs( SI_E1AP_DT_PDU_M4Configuration_ExtIEs ** pM4Configuration_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_M6Configuration_ExtIEs( SI_E1AP_DT_PDU_M6Configuration_ExtIEs ** pM6Configuration_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_M7Configuration_ExtIEs( SI_E1AP_DT_PDU_M7Configuration_ExtIEs ** pM7Configuration_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MDT_Configuration_ExtIEs( SI_E1AP_DT_PDU_MDT_Configuration_ExtIEs ** pMDT_Configuration_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MDTMode_ExtIEs( SI_E1AP_DT_PDU_MDTMode_ExtIEs ** pMDTMode_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MT_SDT_Information_ExtIEs( SI_E1AP_DT_PDU_MT_SDT_Information_ExtIEs ** pMT_SDT_Information_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBS_ServiceArea_ExtIEs( SI_E1AP_DT_PDU_MBS_ServiceArea_ExtIEs ** pMBS_ServiceArea_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBS_ServiceAreaInformation_ExtIEs( SI_E1AP_DT_PDU_MBS_ServiceAreaInformation_ExtIEs ** pMBS_ServiceAreaInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBS_ServiceAreaTAIList_Item_ExtIEs( SI_E1AP_DT_PDU_MBS_ServiceAreaTAIList_Item_ExtIEs ** pMBS_ServiceAreaTAIList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_MBS_ServiceAreaInformationItem_ExtIEs( SI_E1AP_DT_PDU_MBS_ServiceAreaInformationItem_ExtIEs ** pMBS_ServiceAreaInformationItem_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_NGRANAllocationAndRetentionPriority_ExtIEs( SI_E1AP_DT_PDU_NGRANAllocationAndRetentionPriority_ExtIEs ** pNGRANAllocationAndRetentionPriority_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_NG_RAN_QoS_Support_Item_ExtIEs( SI_E1AP_DT_PDU_NG_RAN_QoS_Support_Item_ExtIEs ** pNG_RAN_QoS_Support_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Non_Dynamic5QIDescriptor_ExtIEs( SI_E1AP_DT_PDU_Non_Dynamic5QIDescriptor_ExtIEs ** pNon_Dynamic5QIDescriptor_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_NPNSupportInfo_ExtIEs( SI_E1AP_DT_PDU_NPNSupportInfo_ExtIEs ** pNPNSupportInfo_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_NPNSupportInfo_SNPN_ExtIEs( SI_E1AP_DT_PDU_NPNSupportInfo_SNPN_ExtIEs ** pNPNSupportInfo_SNPN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_NPNContextInfo_ExtIEs( SI_E1AP_DT_PDU_NPNContextInfo_ExtIEs ** pNPNContextInfo_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_NPNContextInfo_SNPN_ExtIEs( SI_E1AP_DT_PDU_NPNContextInfo_SNPN_ExtIEs ** pNPNContextInfo_SNPN_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_NR_CGI_ExtIEs( SI_E1AP_DT_PDU_NR_CGI_ExtIEs ** pNR_CGI_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_NR_CGI_Support_Item_ExtIEs( SI_E1AP_DT_PDU_NR_CGI_Support_Item_ExtIEs ** pNR_CGI_Support_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Extended_NR_CGI_Support_Item_ExtIEs( SI_E1AP_DT_PDU_Extended_NR_CGI_Support_Item_ExtIEs ** pExtended_NR_CGI_Support_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_N6JitterInformationExtIEs( SI_E1AP_DT_PDU_N6JitterInformationExtIEs ** pN6JitterInformationExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PacketErrorRate_ExtIEs( SI_E1AP_DT_PDU_PacketErrorRate_ExtIEs ** pPacketErrorRate_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDCP_Configuration_ExtIEs( SI_E1AP_DT_PDU_PDCP_Configuration_ExtIEs ** pPDCP_Configuration_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDCP_Count_ExtIEs( SI_E1AP_DT_PDU_PDCP_Count_ExtIEs ** pPDCP_Count_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Data_Usage_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Data_Usage_Item_ExtIEs ** pPDU_Session_Resource_Data_Usage_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDCP_SN_Status_Information_ExtIEs( SI_E1AP_DT_PDU_PDCP_SN_Status_Information_ExtIEs ** pPDCP_SN_Status_Information_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DRBBStatusTransfer_ExtIEs( SI_E1AP_DT_PDU_DRBBStatusTransfer_ExtIEs ** pDRBBStatusTransfer_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Activity_ItemExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Activity_ItemExtIEs ** pPDU_Session_Resource_Activity_ItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Confirm_Modified_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Confirm_Modified_Item_ExtIEs ** pPDU_Session_Resource_Confirm_Modified_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Failed_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Failed_Item_ExtIEs ** pPDU_Session_Resource_Failed_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Failed_Mod_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Failed_Mod_Item_ExtIEs ** pPDU_Session_Resource_Failed_Mod_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Failed_To_Modify_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Failed_To_Modify_Item_ExtIEs ** pPDU_Session_Resource_Failed_To_Modify_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Modified_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Modified_Item_ExtIEs ** pPDU_Session_Resource_Modified_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Required_To_Modify_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Required_To_Modify_Item_ExtIEs ** pPDU_Session_Resource_Required_To_Modify_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Setup_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Setup_Item_ExtIEs ** pPDU_Session_Resource_Setup_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_Setup_Mod_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_Setup_Mod_Item_ExtIEs ** pPDU_Session_Resource_Setup_Mod_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_To_Modify_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_To_Modify_Item_ExtIEs ** pPDU_Session_Resource_To_Modify_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_To_Remove_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_To_Remove_Item_ExtIEs ** pPDU_Session_Resource_To_Remove_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_To_Setup_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_To_Setup_Item_ExtIEs ** pPDU_Session_Resource_To_Setup_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_Resource_To_Setup_Mod_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_Resource_To_Setup_Mod_Item_ExtIEs ** pPDU_Session_Resource_To_Setup_Mod_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDU_Session_To_Notify_Item_ExtIEs( SI_E1AP_DT_PDU_PDU_Session_To_Notify_Item_ExtIEs ** pPDU_Session_To_Notify_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDUSetQoSParameters_ExtIEs( SI_E1AP_DT_PDU_PDUSetQoSParameters_ExtIEs ** pPDUSetQoSParameters_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_PDUSetQoSInformation_ExtIEs( SI_E1AP_DT_PDU_PDUSetQoSInformation_ExtIEs ** pPDUSetQoSInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoS_Characteristics_ExtIEs( SI_E1AP_DT_PDU_QoS_Characteristics_ExtIEs ** pQoS_Characteristics_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoS_Flow_Item_ExtIEs( SI_E1AP_DT_PDU_QoS_Flow_Item_ExtIEs ** pQoS_Flow_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoS_Flow_Failed_Item_ExtIEs( SI_E1AP_DT_PDU_QoS_Flow_Failed_Item_ExtIEs ** pQoS_Flow_Failed_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoS_Flow_Mapping_Item_ExtIEs( SI_E1AP_DT_PDU_QoS_Flow_Mapping_Item_ExtIEs ** pQoS_Flow_Mapping_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoS_Parameters_Support_List_ItemExtIEs( SI_E1AP_DT_PDU_QoS_Parameters_Support_List_ItemExtIEs ** pQoS_Parameters_Support_List_ItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoS_Flow_QoS_Parameter_Item_ExtIEs( SI_E1AP_DT_PDU_QoS_Flow_QoS_Parameter_Item_ExtIEs ** pQoS_Flow_QoS_Parameter_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoSFlowLevelQoSParameters_ExtIEs( SI_E1AP_DT_PDU_QoSFlowLevelQoSParameters_ExtIEs ** pQoSFlowLevelQoSParameters_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoS_Flow_Removed_Item_ExtIEs( SI_E1AP_DT_PDU_QoS_Flow_Removed_Item_ExtIEs ** pQoS_Flow_Removed_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_QoS_Flows_to_be_forwarded_Item_ExtIEs( SI_E1AP_DT_PDU_QoS_Flows_to_be_forwarded_Item_ExtIEs ** pQoS_Flows_to_be_forwarded_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_DataForwardingtoNG_RANQoSFlowInformationList_Item_ExtIEs( SI_E1AP_DT_PDU_DataForwardingtoNG_RANQoSFlowInformationList_Item_ExtIEs ** pDataForwardingtoNG_RANQoSFlowInformationList_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_RedundantPDUSessionInformation_ExtIEs( SI_E1AP_DT_PDU_RedundantPDUSessionInformation_ExtIEs ** pRedundantPDUSessionInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_ROHC_Parameters_ExtIEs( SI_E1AP_DT_PDU_ROHC_Parameters_ExtIEs ** pROHC_Parameters_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_ROHC_ExtIEs( SI_E1AP_DT_PDU_ROHC_ExtIEs ** pROHC_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_SecurityAlgorithm_ExtIEs( SI_E1AP_DT_PDU_SecurityAlgorithm_ExtIEs ** pSecurityAlgorithm_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_SecurityIndication_ExtIEs( SI_E1AP_DT_PDU_SecurityIndication_ExtIEs ** pSecurityIndication_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_SecurityInformation_ExtIEs( SI_E1AP_DT_PDU_SecurityInformation_ExtIEs ** pSecurityInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_SecurityResult_ExtIEs( SI_E1AP_DT_PDU_SecurityResult_ExtIEs ** pSecurityResult_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Slice_Support_Item_ExtIEs( SI_E1AP_DT_PDU_Slice_Support_Item_ExtIEs ** pSlice_Support_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_SNSSAI_ExtIEs( SI_E1AP_DT_PDU_SNSSAI_ExtIEs ** pSNSSAI_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_SDAP_Configuration_ExtIEs( SI_E1AP_DT_PDU_SDAP_Configuration_ExtIEs ** pSDAP_Configuration_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_TNL_AvailableCapacityIndicator_ExtIEs( SI_E1AP_DT_PDU_TNL_AvailableCapacityIndicator_ExtIEs ** pTNL_AvailableCapacityIndicator_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_TSCTrafficCharacteristics_ExtIEs( SI_E1AP_DT_PDU_TSCTrafficCharacteristics_ExtIEs ** pTSCTrafficCharacteristics_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_TSCAssistanceInformation_ExtIEs( SI_E1AP_DT_PDU_TSCAssistanceInformation_ExtIEs ** pTSCAssistanceInformation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_TraceActivation_ExtIEs( SI_E1AP_DT_PDU_TraceActivation_ExtIEs ** pTraceActivation_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_T_ReorderingTimer_ExtIEs( SI_E1AP_DT_PDU_T_ReorderingTimer_ExtIEs ** pT_ReorderingTimer_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Transport_Layer_Address_Info_ExtIEs( SI_E1AP_DT_PDU_Transport_Layer_Address_Info_ExtIEs ** pTransport_Layer_Address_Info_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Transport_UP_Layer_Addresses_Info_To_Add_ItemExtIEs( SI_E1AP_DT_PDU_Transport_UP_Layer_Addresses_Info_To_Add_ItemExtIEs ** pTransport_UP_Layer_Addresses_Info_To_Add_ItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_Transport_UP_Layer_Addresses_Info_To_Remove_ItemExtIEs( SI_E1AP_DT_PDU_Transport_UP_Layer_Addresses_Info_To_Remove_ItemExtIEs ** pTransport_UP_Layer_Addresses_Info_To_Remove_ItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_UDC_Parameters_ExtIEs( SI_E1AP_DT_PDU_UDC_Parameters_ExtIEs ** pUDC_Parameters_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_UE_associatedLogicalE1_ConnectionItemExtIEs( SI_E1AP_DT_PDU_UE_associatedLogicalE1_ConnectionItemExtIEs ** pUE_associatedLogicalE1_ConnectionItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_UESliceMaximumBitRateItem_ExtIEs( SI_E1AP_DT_PDU_UESliceMaximumBitRateItem_ExtIEs ** pUESliceMaximumBitRateItem_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_ULUPTNLAddressToUpdateItemExtIEs( SI_E1AP_DT_PDU_ULUPTNLAddressToUpdateItemExtIEs ** pULUPTNLAddressToUpdateItemExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_UP_Parameters_Item_ExtIEs( SI_E1AP_DT_PDU_UP_Parameters_Item_ExtIEs ** pUP_Parameters_Item_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_UPSecuritykey_ExtIEs( SI_E1AP_DT_PDU_UPSecuritykey_ExtIEs ** pUPSecuritykey_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_UP_TNL_Information_ExtIEs( SI_E1AP_DT_PDU_UP_TNL_Information_ExtIEs ** pUP_TNL_Information_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_UplinkOnlyROHC_ExtIEs( SI_E1AP_DT_PDU_UplinkOnlyROHC_ExtIEs ** pUplinkOnlyROHC_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_UserPlaneFailureIndication_ExtIEs( SI_E1AP_DT_PDU_UserPlaneFailureIndication_ExtIEs ** pUserPlaneFailureIndication_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_ResetType_ExtIEs( SI_E1AP_DT_PDU_ResetType_ExtIEs ** pResetType_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_System_BearerContextSetupRequest_ExtIEs( SI_E1AP_DT_PDU_System_BearerContextSetupRequest_ExtIEs ** pSystem_BearerContextSetupRequest_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_BearerContextSetupRequest( SI_E1AP_DT_PDU_EUTRAN_BearerContextSetupRequest ** pEUTRAN_BearerContextSetupRequest); //  L:11204
void __si_e1ap__set_testdata__PDU_NG_RAN_BearerContextSetupRequest( SI_E1AP_DT_PDU_NG_RAN_BearerContextSetupRequest ** pNG_RAN_BearerContextSetupRequest); //  L:11204
void __si_e1ap__set_testdata__PDU_System_BearerContextSetupResponse_ExtIEs( SI_E1AP_DT_PDU_System_BearerContextSetupResponse_ExtIEs ** pSystem_BearerContextSetupResponse_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_BearerContextSetupResponse( SI_E1AP_DT_PDU_EUTRAN_BearerContextSetupResponse ** pEUTRAN_BearerContextSetupResponse); //  L:11204
void __si_e1ap__set_testdata__PDU_NG_RAN_BearerContextSetupResponse( SI_E1AP_DT_PDU_NG_RAN_BearerContextSetupResponse ** pNG_RAN_BearerContextSetupResponse); //  L:11204
void __si_e1ap__set_testdata__PDU_System_BearerContextModificationRequest_ExtIEs( SI_E1AP_DT_PDU_System_BearerContextModificationRequest_ExtIEs ** pSystem_BearerContextModificationRequest_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_BearerContextModificationRequest( SI_E1AP_DT_PDU_EUTRAN_BearerContextModificationRequest ** pEUTRAN_BearerContextModificationRequest); //  L:11204
void __si_e1ap__set_testdata__PDU_NG_RAN_BearerContextModificationRequest( SI_E1AP_DT_PDU_NG_RAN_BearerContextModificationRequest ** pNG_RAN_BearerContextModificationRequest); //  L:11204
void __si_e1ap__set_testdata__PDU_System_BearerContextModificationResponse_ExtIEs( SI_E1AP_DT_PDU_System_BearerContextModificationResponse_ExtIEs ** pSystem_BearerContextModificationResponse_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_BearerContextModificationResponse( SI_E1AP_DT_PDU_EUTRAN_BearerContextModificationResponse ** pEUTRAN_BearerContextModificationResponse); //  L:11204
void __si_e1ap__set_testdata__PDU_NG_RAN_BearerContextModificationResponse( SI_E1AP_DT_PDU_NG_RAN_BearerContextModificationResponse ** pNG_RAN_BearerContextModificationResponse); //  L:11204
void __si_e1ap__set_testdata__PDU_System_BearerContextModificationRequired_ExtIEs( SI_E1AP_DT_PDU_System_BearerContextModificationRequired_ExtIEs ** pSystem_BearerContextModificationRequired_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_BearerContextModificationRequired( SI_E1AP_DT_PDU_EUTRAN_BearerContextModificationRequired ** pEUTRAN_BearerContextModificationRequired); //  L:11204
void __si_e1ap__set_testdata__PDU_NG_RAN_BearerContextModificationRequired( SI_E1AP_DT_PDU_NG_RAN_BearerContextModificationRequired ** pNG_RAN_BearerContextModificationRequired); //  L:11204
void __si_e1ap__set_testdata__PDU_System_BearerContextModificationConfirm_ExtIEs( SI_E1AP_DT_PDU_System_BearerContextModificationConfirm_ExtIEs ** pSystem_BearerContextModificationConfirm_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_BearerContextModificationConfirm( SI_E1AP_DT_PDU_EUTRAN_BearerContextModificationConfirm ** pEUTRAN_BearerContextModificationConfirm); //  L:11204
void __si_e1ap__set_testdata__PDU_NG_RAN_BearerContextModificationConfirm( SI_E1AP_DT_PDU_NG_RAN_BearerContextModificationConfirm ** pNG_RAN_BearerContextModificationConfirm); //  L:11204
void __si_e1ap__set_testdata__PDU_System_GNB_CU_UP_CounterCheckRequest_ExtIEs( SI_E1AP_DT_PDU_System_GNB_CU_UP_CounterCheckRequest_ExtIEs ** pSystem_GNB_CU_UP_CounterCheckRequest_ExtIEs); //  L:11204
void __si_e1ap__set_testdata__PDU_EUTRAN_GNB_CU_UP_CounterCheckRequest( SI_E1AP_DT_PDU_EUTRAN_GNB_CU_UP_CounterCheckRequest ** pEUTRAN_GNB_CU_UP_CounterCheckRequest); //  L:11204
void __si_e1ap__set_testdata__PDU_NG_RAN_GNB_CU_UP_CounterCheckRequest( SI_E1AP_DT_PDU_NG_RAN_GNB_CU_UP_CounterCheckRequest ** pNG_RAN_GNB_CU_UP_CounterCheckRequest); //  L:11204
void __si_e1ap__set_testdata__PDU_UE_associatedLogicalE1_ConnectionItemRes( SI_E1AP_DT_PDU_UE_associatedLogicalE1_ConnectionItemRes ** pUE_associatedLogicalE1_ConnectionItemRes); //  L:11204
void __si_e1ap__set_testdata__PDU_UE_associatedLogicalE1_ConnectionItemResAck( SI_E1AP_DT_PDU_UE_associatedLogicalE1_ConnectionItemResAck ** pUE_associatedLogicalE1_ConnectionItemResAck); //  L:11204
void __si_e1ap__set_testdata__PDU_SupportedPLMNs_ExtIEs( SI_E1AP_DT_PDU_SupportedPLMNs_ExtIEs ** pSupportedPLMNs_ExtIEs); //  L:11204


void __si_e1ap__Send_Reset_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_ResetAcknowledge_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_ErrorIndication_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_UP_E1SetupRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_UP_E1SetupResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_UP_E1SetupFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_CP_E1SetupRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_CP_E1SetupResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_CP_E1SetupFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_UP_ConfigurationUpdate_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_UP_ConfigurationUpdateAcknowledge_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_UP_ConfigurationUpdateFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_CP_ConfigurationUpdate_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_CP_ConfigurationUpdateAcknowledge_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_CP_ConfigurationUpdateFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_E1ReleaseRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_E1ReleaseResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextSetupRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextSetupResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextSetupFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextModificationRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextModificationResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextModificationFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextModificationRequired_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextModificationConfirm_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextReleaseCommand_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextReleaseComplete_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextReleaseRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BearerContextInactivityNotification_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_DLDataNotification_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_ULDataNotification_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_DataUsageReport_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_UP_CounterCheckRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_UP_StatusIndication_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_PrivateMessage_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_GNB_CU_CPMeasurementResultsInformation_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MRDC_DataUsageReport_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_DeactivateTrace_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_TraceStart_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_ResourceStatusRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_ResourceStatusResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_ResourceStatusFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_ResourceStatusUpdate_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_IAB_UPTNLAddressUpdate_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_IAB_UPTNLAddressUpdateAcknowledge_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_IAB_UPTNLAddressUpdateFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_CellTrafficTrace_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_EarlyForwardingSNTransfer_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_IABPSKNotification_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextSetupRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextSetupResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextSetupFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextModificationRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextModificationResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextModificationFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextModificationRequired_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextModificationConfirm_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextReleaseCommand_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextReleaseComplete_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_BCBearerContextReleaseRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextSetupRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextSetupResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextSetupFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextModificationRequest_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextModificationResponse_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextModificationFailure_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextModificationRequired_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextModificationConfirm_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerNotification_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextReleaseCommand_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextReleaseComplete_Prototype( SI_E1APNode * node);
void __si_e1ap__Send_MCBearerContextReleaseRequest_Prototype( SI_E1APNode * node);


#endif


